### ISSUE TITLE
Server config.json out of date

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#102]
The config.json file located [here](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/backend/config.json) is out of date with the backendConfig schema and current [documentation](https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/serverConfig.md). I'd also consider moving this file out to `backend/` (or just removing it completely) while compressing both the Server Config and Course Config documentation pages into one since the Server Config is _technically_ Course Config at the root level.

**Comment by mwest1066** [comment]
Thanks for the bug report!

Fixed in a42de1c856c85b04aa875812d95b02a2eedda91a

I think server config and course config are quite different (they have different config file formats) and they are done by different people in deployment (a course instructor/TA controls the course config, while the server admin controls the server config).

If the docs are unclear on the distinction between course and server configs then let me know and we'll try and clarify them.
