### ISSUE TITLE
Group assignments in example course cannot be started in student view

### ISSUE THREAD

**Issue by nritschel** [PrairieLearn/PrairieLearn#10788]
It is possible to view the group assignments in the example course as an instructor, but when trying to enter them in student view, an error message says that one has to be enrolled in the course to create a team.

![Image](https://github.com/user-attachments/assets/4a17a49e-5e63-4f2e-9eed-64a9d0b98c71)

Without doing much more digging, it seems that some people (older accounts?) are actually enrolled in the course, so when I brought this up with @mwest1066, he said that he had no issue starting the assignment. However, as a newer user, I do not seem to be enrolled and do not have any role in the course instance. I assume that all access to only handled via the hardcoded overrides for the example course and that this specific interaction is missing such an override?

![Image](https://github.com/user-attachments/assets/e3e9dbb9-91ac-481d-8c47-04c9ff109432)

This might seem like a corner case, but I browsing the example course without setting up their own course or running a local instance is likely the first place where new users try to explore the features of PL. The group assignments in particular are also not that interesting from the instructor view, so being able to try them as a student seems like a fairly important demoing feature to me.

**Comment by mwest1066** [comment]
I'll note that I can't replicate, which is presumably a side-effect of the fact that I'm actually enrolled in the example course? So this might be something that only affects new users? Are users still able to enroll in the example course, or do we block this?

**Comment by jonatanschroeder** [comment]
The check for this is here:
https://github.com/PrairieLearn/PrairieLearn/blob/b62c1b3fb7679242b7b3aa0dc7011897569bccec/apps/prairielearn/src/lib/groups.ts#L215-L234

Note that the check to see if the user is an instructor is done with the `users_is_instructor_in_course_instance` sproc, which doesn't have special handling for the example course. So if we want to allow users with access to the example course to be able to add a group, we would need to do one of these things:

1. Update the sproc to return true if the course is the example course and the user has permission to access the example course (i.e., the user is an instructor in any course). This would require revisiting all uses of this sproc to ensure this doesn't affect their expected functionality. Since this is used in a bunch of queries, I believe it would affect the performance of these queries, which is probably not ideal.
2. Update the group library to consider any user with instructor access in any course (there is [a model function for that check](https://github.com/PrairieLearn/PrairieLearn/blob/b62c1b3fb7679242b7b3aa0dc7011897569bccec/apps/prairielearn/src/models/course-permissions.ts#L214)) if the course is the example course.
3. Update the group library to allow any user to be part of a group if the course is the example course.

Personally I'd advocate for option 2.

**Comment by jonatanschroeder** [comment]
And @mwest1066 you are not seeing this problem because any user with administrator role automatically gets instructor access in any course (via the sproc above).

**Comment by mwest1066** [comment]
> And [@mwest1066](https://github.com/mwest1066) you are not seeing this problem because any user with administrator role automatically gets instructor access in any course (via the sproc above).

Ah yes, makes sense, thanks!
