### ISSUE TITLE
[Feature Request] Provide Questions from a Template

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1121]
Current status-quo is to copy and paste an existing question variant to create a new one leading to a bunch of UUID issues or naming faults. 

I was thinking adding something along the lines of:

```bash
pl --qtype="pl_element" --name= "Version Control" --copy-to="questions/"
```

Spawn a `pl_element` with `name` and attempt to resolve into the `questions/` directory? Probably need some initial `pwd` check if it matches `pl-courseXXX` setup.

**Comment by coatless** [comment]
Any objection to a NodeJS app?

**package.json**
```js
{
  "name": "pl",
  "version": "1.0.0",
  "description": "Create a PrairieLearn Question from Element Templates",
  "bin" : {
    "pl" : "./pl-question-template.js"
  },
  "license": "AGPL"
}
```

**pl-question-template.js**

```js
#!/usr/bin/env node
const [,, ... args] = process.args

console.log(`Arguments passed: ${args}`)
```

Add CLI options via `Commander.js`

Install would then be done with:

```
npm link
```

This would give:

```bash
pl --question-type="mc" --name="DBProperties"
```

c.f.

- https://docs.npmjs.com/creating-node-js-modules
- https://scotch.io/tutorials/build-an-interactive-command-line-application-with-nodejs
- https://codeburst.io/building-a-node-js-interactive-cli-3cb80ed76c86
- https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/

**Comment by trombonekenny** [comment]
Similar but could be wrapped into this:

I'd wanted something that bootstrapped a whole PL course directory. Something you could point at an empty directory and have it make the minimum required files to start loading. Bonus points for adding sample questions how you described. It would need to be careful not to overwrite things, etc.

I was thinking about running it as a command-line interaction from the PrairieLearn dev-mode console. @nwalters512 had talked about something standalone. Maybe we could make both work? (A mostly external tool that can be run from inside the PL console too). Running these tools from inside PL is helpful because it already would have the needed software installed in the container, doesn't vary by OS (newlines, paths) and has known locations for /course, etc. The `tools/generate_uuids.py` script is useful but it's not easy for new people to be able to run it.

There are other things that would be useful to trigger from inside PL, like pointing to multiple /course directories (rewriting the config.json), running npm update, checking a cloud source to see if the docker version is the latest version or if an update is needed, etc.

**Comment by coatless** [comment]
How about:

```
pl --create-course="deptXXX"
```

Output:

```
✔ Creating 'pl-deptXXX/'
✔ Setting active project to 'pl-deptXXX'
✔ Initializing Git Repository
✔ Setting remote to 'prairielearn/pl-deptXXX'
✔ Writing 'infoCourse.json'
✔ Creating 'questions/'
● Call `pl --question-type --help` to view list of question templates.
✔ Creating 'courseInstance/sp19'
✔ Writing 'courseInstance/sp19/infoCourseInstance.json'
● Add course staff and set permission levels to 'courseInstance/sp19/infoCourseInstance.json'.
✔ Creating 'courseInstance/sp19/assessments'
● Call `pl --assessment --help` to view assessment types possible.
```

**Comment by nwalters512** [comment]
I would prefer something standalone. Note that `pl` is a command on macOS, so we'd want a different name to avoid collisions. `plearn`? `plrn`? Just super verbose `prairielearn`?

**Comment by coatless** [comment]
Ahh yes, the property inspector... 

Short commands are better as they will be typed... Alot. 

How about:

- `pli`
- `plcli`
- `plt`

**Comment by nwalters512** [comment]
`pli` is kind of a fun reference to CLI. Definitely agree it should be short!

**Comment by coatless** [comment]
So, I've begun the process to implement the example templates and course setup via an _R_ package. The _R_ package functionality can be accessed via a node script if need be. c.f. https://colinfay.me/create-r-cli-npm/

The benefits to this approach are:

1. tags and topics can be verified during question deployment.
2. 
3. easy template use and modification

Potentially, I'll try my hand at using `asciidocs` instead of the PL file-specific files.

Sample question creation of a fixed MC question.

![plearn-deploy-mc-question](https://user-images.githubusercontent.com/833642/62676997-4534a880-b972-11e9-851a-b3a4d6880d59.gif)

**Comment by mwest1066** [comment]
Very cool!

I apologize for saying this when you are doing great work, but another implementation possibility would be to build this directly into the PL web interface. This would fit naturally with @tbretl’s question editing code, and it would work both in local dev in docker and on the production web server. For example, on the Questions page there could be a “New question” button that leads to the above functionality. I feel like this would have a very high use-rate from users. Of course it would require writing in JS rather than in R 😄
