### ISSUE TITLE
"The grading results were larger than 100KiB..."

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1153]
This error and it's accompanying message are fairly confusing. It suggests removing print statements from your code, but it can be triggered by error messages that don't result from print statements. (In this case a student had accidentally implemented a recursive class constructor with no base case.) It's also unclear what the course staff or a proctor is going to do about the situation.

Better behavior would be to just display truncated output, since in the case of runaway repetitive error messages seeing a few is sufficient to understand what the problem is.

**Comment by nwalters512** [comment]
Fair point that this is somewhat confusing and undocumented behavior; I'll add notes about this to my documentation update PR. However, it's ultimately on you to truncate your own output. The 100KB limit is on the size of your `results.json`. Given that we treat that as a black box (we neither know nor care what you put in there, for the most part), we can't just go arbitrarily trimming strings on your behalf.

**Comment by mwest1066** [comment]
I wonder if we should do something hacky like find large strings in the JSON and truncate them? If the string is a base64-image file (for example) then this will corrupt it, but that might be better than getting no output. We could also force a grading fail at the same time?

Of course it would be better if courses truncated data from the grading container, but I think that realistically people will either not know to do this (even with docs) or will forget sometimes.

**Comment by nwalters512** [comment]
The base64 encoding issue is the primary reason I don't feel comfortable doing this. Although honestly, that use case might make it worth reevaluating our limits - IIRC, some 357 assignments produced multiple graphs, which might not fit in the current limit. @mwest1066 can you offer any insight into how Relate stores + handles images produced by code?

**Comment by mwest1066** [comment]
I agree that we are going to need to increase our limits in any case (maybe a couple of MB?). I'm not sure what model Relate uses for storing files. I'm fine to stick with base64 (it's only a 33% overhead in file size) and PNG output from a plot is generally sub-100 kB.

This doesn't really address the issue of what to do with over-size output, though. Even if we increase the limit people are going to hit it.

I agree it's much easier for the course graders to do the right thing, because they know the meaning of the fields and which ones can be truncated without loss.

If we truncate some base64 data can we easily fail the job, make the error indicate that output was truncated, but still let the question attempt to render the output anyway?

**Comment by nwalters512** [comment]
Currently, jobs that are failed at the PG level and not the course level aren't given the chance to render at all. I guess we could differentiate between types of failures? That's adding some complexity though. There's also the question of what to do when there isn't one extremely log field, but lots of smaller ones that collectively put us over the limit. Figuring out heuristics to decide what to trim gets annoying really fast, which is why I avoided that problem entirely by just failing the job.

**Comment by gchallen** [comment]
@nwalters512: we can definitely truncate the results ourselves, and probably will. But I thought that the `results.json` had more structure to it than you're implying. Perhaps there is a way for custom grading servers to interpret the results in custom ways, but it seems like there is a default format with an `output` field, `tests` array, etc. In that case, if truncating the `output` field can bring the result down in size maybe that's the right thing to do? (Assuming you don't move to another approach for saving these files.)

**Comment by nwalters512** [comment]
This could perhaps be clearer in the docs, but the only required fields in that JSON are `score` and `succeeded`. If you use the structure that you're using, you can take advantage of the provided results rendering element, but it's still largely schemaless. I'm hesitant to start special-casing - because then someone will invent a new structure and want that to be auto-truncated as well, and so on. 

Aim for truncating your output for now - we'll let you know if things change in the future.

**Comment by trombonekenny** [comment]
This size limit was updated recently, right?

**Comment by nwalters512** [comment]
Yep - it's now 1MB, and I removed the message about "try removing log statements".
