### ISSUE TITLE
Optimize element rendering in question

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1167]
Currently, elements are rendered by iterating over the name of all known elements and rend ring all elements of the same type at once. However, this represents potentially wasted work, as some elements might be inside another element the conditionally renders depending on the panel. We should instead parse the question html into a tree and pre-prune any subtrees that won't ultimately be displayed for the given panel.

**Comment by mwest1066** [comment]
Related to this, the upgrade to `cheerio.js` (and associated upgrade to `htmlparser2` that it uses) exposed another wrinkle in how we parse HTML — namely that the upgrade changed the auto-closing behavior on some tags, so we no longer auto-close `<p>` when we get a closing `</pl_question_panel>’. This resulted in an incorrect parsed HTML structure being returned. I patched the specific issue in `exampleCourse/questions/addNumbers` by adding closing '</p>' tags, but this issue is probably going to break some existing course questions.

To fix it, my current thought is to not use the `Parser` from `htmlparser2` but rather to reimplement it ourselves. We can still use their `Tokenizer`, but we want different behavior when parsing. Specifically, we need to:

* Handle `pl_*` element auto-closing behavior correctly. All `pl_*` closing tags should auto-close open `<p>` elements, I think, and maybe more changes. This is essentially equivalent to modifying the `openImpliesClose` list at https://github.com/fb55/htmlparser2/blob/master/lib/Parser.js#L36
* Report many more errors. Most HTML parsers (like `htmlparser2`) are quite forgiving so they can handle web-scraping, but for our use-case I think we should be much more strict.

**Comment by mwest1066** [comment]
Fixed by @nwalters512 in b55146306d9174f9a497cd3aaea32fd0adae64cd
