### ISSUE TITLE
Dark/Night theme

### ISSUE THREAD

**Issue by adbX** [PrairieLearn/PrairieLearn#1190]
Is there a dark/night theme for prarielearn? If not, I'd like to start working on it!

**Comment by echuber2** [comment]
Haha, I love this.

**Comment by adbX** [comment]
I'm not much of a web dev so if any has any pointers/tips it would be much appreciated!

**Comment by nwalters512** [comment]
Nope, there's no night theme :P and I'm not sure if this is actually desired. If courses make assumptions about their content being shown on a white background and suddenly it's on a dark one, that could make for a very bad experience for students. There's a lot of potential edge cases, and then we suddenly have to support two themes with all our elements and custom styles. That's a lot of work.

But feel free to try to change my mind! We use pretty much vanilla Bootstrap for the entire site. https://bootswatch.com/darkly/ looks promising - the tricky part is figuring out how to apply only one set of styles at page render time. This would probably be a user preference?

**Comment by echuber2** [comment]
Increasingly I see sites with a light/dark toggle on the page in the margin or headers, and a lot of the time it doesn't seem to reload the page to take effect. If this were added it would probably be crucial to not reload the page, because that could definitely mess up some student work in progress.

**Comment by echuber2** [comment]
If question content could be impacted, maybe any theme should only apply to the PL margins, controls, and header/footer. There could be a way for instructors to mark specific question content dark-allowed but it seems like there are other ways to deal with that (e.g. hand out a reading prompt as a PDF download). The ace editor has its own theme support and instructors could script a toggle on that already if they wanted.

Also good to keep in mind the CBTF has viewing angle filters on the screens that make the screen darker and impart a reddish hue.

**Comment by nwalters512** [comment]
Those people with said toggles also control their own CSS, something we (for better or for worse) don't do. If we were building our own style system, we could pretty easily design for that.

**Comment by adbX** [comment]
Good point on not having it not reload. Questions with non-transparent images would also be an issue. I guess I'll try to play with the CSS for now using something like Stylish or GreaseMonkey.

**Comment by echuber2** [comment]
It looks like work was begun at #2108 but note, it's not trivial for a dark theme to be officially and fully supported because of accessibility issues and other glitches it may raise. PL elements can do their own thing with styles and these may not go along well with a dark site theme. So basically, it's easier said than done.

On a per-user basis, browser plugins that allow style overrides such as Stylus (note: not Stylish, it's spyware) or Dark Reader will let you apply a custom dark theme to PL, although imperfect.

**Comment by nwalters512** [comment]
Going to close this issue out - while I am personally a fan of dark mode and use it when I can, PrairieLearn is fundamentally not built in a way to make this sustainable. In a hypothetical future where we're not using Bootstrap and elements and questions are built with a more consistent UI framework, I'd love to do this.
