### ISSUE TITLE
Add check for duplicate answers to MC questions

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1228]
In tests?
Or on sync?
Or both?

**Comment by mwest1066** [comment]
On sync is probably the best time to do it. Catch it early.

**Comment by nwalters512** [comment]
This was being worked on at HackIL, hopefully we get a PR soon!

**Comment by trombonekenny** [comment]
Cool, I look forward to seeing it!

**Comment by trombonekenny** [comment]
One of the things I realized from reviewing a PHYS 10x question last week is that sometimes auto-generated distractors can repeat. I wonder if there's something we could do at the question generation level to inspect for this and take action (invalidate and make a new variant?)

That's not the same as duplicated manual answers, but shows up the same to the student.

**Comment by nwalters512** [comment]
Agree that would be nice, but it would be difficult to differentiate between "the question is fundamentally broken" and "just this variant is bad, we can regenerate". I'd prefer to just encourage people to a) be aware of that when and b) use "test 100 times" a lot to check for edge cases.

**Comment by mwest1066** [comment]
I actually think the right place to do this is in `prepare()`, so it will be caught very early.

**Comment by firasm** [comment]
I was thinking of taking a stab at this issue since it hits my students often in some ultra-randomized "sig fig" type questions where they have to choose the right answer with different errors.

IMHO, I think an error should be thrown if there are multiple choice options whose string representations are exactly identical. That way, students will see a regenerate variant button right away.

Does that make sense as the expected outcome?

<img width="844" alt="138740089-88174492-226d-4c42-a8b7-d71a7c761f0a" src="https://user-images.githubusercontent.com/2507459/180921383-e8d8d80a-bc65-4c4c-ac50-5b23177a8617.png">

**Comment by mwest1066** [comment]
> IMHO, I think an error should be thrown if there are multiple choice options whose string representations are exactly identical. That way, students will see a regenerate variant button right away.

Yes, this sounds correct to me. I think my [original comment](https://github.com/PrairieLearn/PrairieLearn/issues/1228#issuecomment-417377644) was wrong and it's best to catch this in `generate()` and throw an error if any duplicates are found in the list of answers. Allowing students to regenerate a broken variant will often fix the problem.

**Comment by eliotwrobson** [comment]
> it's best to catch this in `generate()` and throw an error if any duplicates are found in the list of answers.

As commented on the PR for this, elements don't call the `generate()` function, so I think catching duplicates in `prepare()` (as is done currently in the PR) is the way to go.
