### ISSUE TITLE
Instructor question view have same layout as student

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1321]
The `instructorQuestion` view gives the full bootstrap container to the question content. When rendered in student homework or exam contexts, the question is displayed in a narrower `<div class="col-lg-9 col-sm-12"> block.

We should make both of those pages use a consistent layout, even if the right column (used for assessment instance info) is mostly blank or faked.

**Comment by mwest1066** [comment]
Totally agreed. I've been putting this off because I'd ideally like to make the student question content full-width (like the instructor question page). I think the way Relate formats this is nice, with a row of question numbers across the top of the page for fast access to all questions. I'm not sure if we can easily squeeze all the current right-hand-sidebar information into the top of the page, however.
