### ISSUE TITLE
Add tabindex=-1 for math elements

### ISSUE THREAD

**Issue by braeden123** [PrairieLearn/PrairieLearn#1427]
When answering questions on PrairieLearn, using the tab key selects MathJax chars in-between the input boxes. Requiring several tabs to select the next input box.

Hopefully that makes sense, I can explain further if needed

**Comment by trombonekenny** [comment]
Hi @braeden123, thanks for the feedback!

Do you have a URL of a question where you've experienced this? That would help us try out what you're talking about.

**Comment by braeden123** [comment]
@trombonekenny 

Here ya go:

https://prairielearn.engr.illinois.edu/pl/course_instance/21031/instance_question/35853338/

Just select any input box, and try to use the tab key to select down to the next one. Thanks!

**Comment by trombonekenny** [comment]
TIL every MathJax rendering can be right-clicked to bring up a menu of options. For accessibility's sake, that's why those rendered pieces become tab targets. [That could be disabled globally](http://docs.mathjax.org/en/latest/options/hub.html), but it's discouraged because it breaks that menu for some access methods.

I also noticed when I right-clicked on a mathjax render, I could choose Accessibility and uncheck "Include in tab order". I don't know where it saves that config choice in the browser, but it seemed to persist across page reloads and is true for multiple questions that I tried. If you can toggle that off individually and it persists, does that address your issue?

**Comment by braeden123** [comment]
@trombonekenny Hey sorry for the late reply. That worked perfectly, I appreciate it!

And totally makes sense why you don't globally disable it. 

Thanks!
