### ISSUE TITLE
API for Mass Adding/Removing 

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1481]
Goal of the API is to handle mass subscription and mass removal of students. Potential can be used alongside of some kind of active directory dump of student names.

The endpoint could probably be modeled after `courseInstanceGradebook`, c.f.

https://github.com/PrairieLearn/PrairieLearn/tree/master/api/v1/endpoints/courseInstanceGradebook

**Comment by coatless** [comment]
Endpoint Design:

```
/pl/api/v1/course_instances/:course_instance_id/student
```

- `PUT`: Create new student mapping
- `GET`: Check if student is registered
- `DELETE`: Remove student if registered.

Sound okay?

**Comment by mwest1066** [comment]
Does the `.../roster/student` endpoint have some sort of UID on the end of it? So `.../roster/student/<UID>`?

More generally, what’s the use case here? We could alternatively hook up to the actual course rosters (we already do this for PrairieSchedule).

**Comment by coatless** [comment]
I think the use case here was to primarily ensure the student **is enrolled in the course**. 

A secondary use case was simplifying registration. (I know, click a button is easy... )

**Comment by mwest1066** [comment]
I’m not against adding API endpoints for this, and I’ll certainly take PRs that do so. But I guess my first reaction is that we’d be better off adding code to auto-enroll students from course rosters? We already have code like this in PrairieSchedule. That way instructors don’t have to do anything to enroll students, it just happens. Otherwise everyone would have to individually write code to push rosters to the API.

If you want to restrict students to those who are actually enrolled, then that suggests adding an `officially_enrolled` column to the `enrollments` table and setting this to TRUE if we find a student on the official rosters (or I guess an instructor could override this flag). Then we’d also want an access rule so that you could restrict access to only students with this flag set.

**Comment by coatless** [comment]
> we’d be better off adding code to auto-enroll students from course rosters

I agree 100%. I don't think I have access to PrairieSchedule, but it would be a welcome addition. 

I believe this came up during an office hour awhile back when instructors were surprised that non-enrolled students were able to view the assessments. (The instructors were split if this was okay or not.)

**Comment by mwest1066** [comment]
@coatless awesome! I agree this would be a worthwhile feature. I’ll leave it in your hands.
