### ISSUE TITLE
Filing an issue in instructor view signs as student

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1505]
Since there's no other way to leave comments on issues right now, it's convenient(?) for the instructor to add another issue on an item for the sake of leaving a comment visible to other staff. Right now, this tends to sign the instructor's name/email as that of the last student whose response/issue was being reviewed on the same page. It seems that the issue should be signed as the effective user rather than based on the current URL, etc.

**Comment by mwest1066** [comment]
@echuber2 Looks like this is a bug. Want to fix it? I’ve described one possible way to fix it below.

The problem is that we are setting `issues.user_id` (the user filing the issue) to be the same as `variants.user_id` (the user who owns the question). To fix this, we need to:

1. Add an extra argument to `sprocs/issues_insert_for_variant.sql` for `user_id`. We already have `authn_user_id`, but we also will need just plain `user_id`. I suggest adding it as a new second-to-last argument (just before `authn_user_id`). We should be prepared for this argument to be NULL (for automatically reported issues), in which case we should still use the `user_id` from the variant as we do now. But if we are passed a non-NULL `user_id` then we should use it.

2. In all the places we call `issues_insert_for_variants` for manually-reported issues we need to pass the new `user_id` argument as the value `res.locals.user.user_id`. I think these are in `instructorQuestion`, `studentInstanceQuestionExam`, and `studentInstanceQuestionHomework`.

3. In all other places where we call `issues_insert_for_variants` we should pass NULL for `user_id`.

**Comment by jonatanschroeder** [comment]
I believe this is now "fixed" by the fact that an instructor viewing a student question instance cannot create an issue. @mwest1066 or @nwalters512 can you second that to make sure I'm not missing something?

**Comment by nwalters512** [comment]
@jonatanschroeder can confirm, just tested this on the production server. The workflow of adding "another issue on an item for the sake of leaving a comment visible to other staff" is an interesting one (that I think we inadvertently broken with the new auth system (https://xkcd.com/1172/)), but that's outside the scope of this issue.

**Comment by jonatanschroeder** [comment]
> The workflow of adding "another issue on an item for the sake of leaving a comment visible to other staff" is an interesting one (that I think we inadvertently broken with the new auth system (https://xkcd.com/1172/)), but that's outside the scope of this issue.

It's still possible to follow the link to the question (instructor block) and raise an issue there.

**Comment by echuber2** [comment]
I had actually been doing this to comment on other issues themselves, e.g. if a student reports that a question is wrong, I could add an issue to comment "this is intended behavior because..." and then close both.

The ideal would be to have a more extensive issue tracking system with threaded conversations or something.

**Comment by nwalters512** [comment]
> I had actually been doing this to comment on other issues themselves, e.g. if a student reports that a question is wrong, I could add an issue to comment "this is intended behavior because..." and then close both.

This is what I was thinking of too. Agreed that there's a lot we could do to improve the issues tracking system! #4093 (or a new ticket linked there) may be a good place to capture that desire.

**Comment by jonatanschroeder** [comment]
> The ideal would be to have a more extensive issue tracking system with threaded conversations or something.

Check #4093. Cinda and I have a student that is checking a few options related to that.
