### ISSUE TITLE
NaN scores show up as 50% bars on the Assessments list

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#166]

**Comment by mwest1066** [comment]
See pl-cs241 with user angrave on Exam3 (Practice midterm)

![gciciedi](https://cloud.githubusercontent.com/assets/875833/10317640/27200012-6c2b-11e5-91ff-e7a0175b2e5c.png)

From @angrave: "Exam 3: = just a single non-graded file-type question. When clicking finish the score is shown as "100%" (that's another UI bug?) but on the summary page above you can see 50% in the green-red bar."

**Comment by mwest1066** [comment]
At least the case above (50% on Exam 3) is caused by the test having `nQuestions: 2` but only one question listed. When generating the test it tries to choose two questions, but only one is available, so only one question is displayed to the user. The displayed score is computed as `score / nQuestions`, so this ends up being 50%.

@angrave, are there other cases where this bug occurs?

**Comment by angrave** [comment]
Immediately after the student ends the assessment an invalid score is displayed

- Lawrence

On Oct 24, 2015 12:10, Matthew West <notifications@github.com> wrote:

At least the case above (50% on Exam 3) is caused by the test having nQuestions: 2 but only one question listed. When generating the test it tries to choose two questions, but only one is available, so only one question is displayed to the user. The displayed score is computed as score / nQuestions, so this ends up being 50%.

@angrave<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_angrave&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=DvT4PEagC1_uJoK7XYcVznCf9vBnV8AqDdM20MaTLvM&m=mM_eI26KryebJKpeue4XM6uGnabQc8irbWg_ldTcsIg&s=uTBqX2TYThZmw0CaA4PuMbJiJao_b4mFarDvm1xzVHc&e=>, are there other cases where this bug occurs?

**Comment by mwest1066** [comment]
@angrave, I'm afraid that I'm having trouble reproducing this bug. Can you provide detailed repro steps?

I've just logged in to prairielearn.engr and completed Exam 3 and Exam 4 for CS241. In both cases I uploaded a file, saved it, then did "Finish and grade exam". After this the question was displayed as 100% correct, the exam was displayed as 100% correct, and when I go back to the Assessments page it is also listed as 100% correct (except for Exam 3, which is listed as 50% correct due to nQuestions: 2 as explained above).

What am I missing here? How are you getting an invalid score to be displayed?

**Comment by angrave** [comment]
The "100%" is invalid for quiz3 (which has the external question and no PL graded questions)

Students complete quiz3 and they see a score when running a makefile.
- This score may not be 100%

The 100% as reported by PL is completely bogus (and thus confusing and or miss-information - which IMHO is bad bad thing for grade related info);
PL (currently) has no idea what a student earned on that quiz - only that they completed the quiz - and therefore should not attempt to display an authoritative score.

BTW- (one day) PL could parse the question score out of the uploaded zip file. Or better, we are able dispense with the manual upload completely.

Best,
Lawrence
________________________________

**Comment by mwest1066** [comment]
Thanks for the info!

I'm closing this as NOTABUG, because the 100% scores are expected behavior at the moment. There is an open enhancement request for non-scored questions at #50.

Getting real scores for code questions is something that @wadefagen is thinking about.
