### ISSUE TITLE
Fast loading of /testStats causes server crash with exceeded stack size

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#176]
Reported by @tnip

**Comment by mwest1066** [comment]
@tnip, if you have any details about how to reproduce this, or any ideas about what's causing it, would you mind commenting here with details? Thanks!

**Comment by tnip** [comment]
Repro: Refresh multiple times in rapid succession as admin. I've found that doing a couple refreshs on the Sync page with maybe a second or two in-between to get the DOM rolling does the job.

Cause: Most likely "premature optimization" caused by the number of aggregate queries being done. (For each exam, for each question... do an average/sum/etc.)

**Comment by tnip** [comment]
Just some more logging.

<img width="1001" alt="screen shot 2015-12-09 at 12 12 44" src="https://cloud.githubusercontent.com/assets/877821/11694214/65b22fb0-9e6e-11e5-9697-efc508b834ea.png">

**Comment by mwest1066** [comment]
Eliminated by PLv2.
