### ISSUE TITLE
Doc inconsistency: `correct_answers` vs. others

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#1865]
The docs for `pl-string-input` have inconsistent examples about what the correct answer parameter should be: https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/elements.md#customizations-5

Is it `correct-answer`, `correct-answers`, or `correct_answers` (as in the example course)?

**Comment by echuber2** [comment]
cf. https://github.com/PrairieLearn/PrairieLearn/blob/master/exampleCourse/questions/elementStringInput/server.py

**Comment by echuber2** [comment]
So it appears that `correct-answer` is the right attribute name for the element itself, but internally the Python default is `data['correct_answers']`. So the inconsistency on the doc is this:

> Correct answer for grading. Defaults to `data["correct-answers"][answers-name]`.

It should be this, right?

> Correct answer for grading. Defaults to `data["correct_answers"][answers-name]`.

@mwest1066 @coatless

**Comment by coatless** [comment]
> Correct answer for grading. Defaults to `data["correct-answers"][answers-name]`.

This is wrong. It should be: `data["correct_answers"][answers-name]`

This is a residue from when style shifted from `snake_case` to `kebab-case`. The declaration of `correct-answer` is came at an earlier time due to a shift from pluralism to singular attributes.

---

Generally, all elements save their result into `data["correct_answers"][answers-name]`. c.f. [creating an element](https://prairielearn.readthedocs.io/en/latest/devElements/#element-functions). But, setting the value via the attribute is done with `correct-answer`.

https://github.com/PrairieLearn/PrairieLearn/blob/fb3fdeb9202efa5fc9e55bd2e7fb9341587d8306/elements/pl-string-input/pl-string-input.py#L28-L33

To further emphasize, note that `correct-answer` is enforced in the attribute check:

https://github.com/PrairieLearn/PrairieLearn/blob/fb3fdeb9202efa5fc9e55bd2e7fb9341587d8306/elements/pl-string-input/pl-string-input.py#L24

**Comment by echuber2** [comment]
Right, so should I update the doc then?

**Comment by coatless** [comment]
@echuber2 already sent it :'(

**Comment by echuber2** [comment]
All good. Thanks.
