### ISSUE TITLE
Fold "Exam" into "RetryExam"

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#197]
At the moment we are maintaining two different exam-type modes:
- `Exam` has each question worth just one point and there is no concept of retrying questions.
- `RetryExam` allows retries and variable points per question.

To minimize code duplication we should eliminate `Exam`. For backwards compatibility we should still allow `Exam`-format info.json files but in `backend/server.js` we should use `checkInfoValid()` to warn that they are deprecated and to transform the `info` object from `Exam` format to `RetryExam` format.

In the student UI, we could detect that there are in fact no retries available and not display any information about this. I'm not sure it's worth it, however. We should be encouraging instructors to allow retries in any case, so maybe we just don't support this old style of exam at all.

**Comment by lotrfan** [comment]
In addition to auto-converting `info.json`, we also probably need to update the `tInstance`s; in particular, there are several things missing from an `Exam` `tInstance` that `RetryExam` expects:

- `questionsByQID` - this can be populated by grabbing things out of `qInstances` and `submissions` (or `submissionsByQID` of the `tInstance`, but that won't work for non-finished `Exam`s)
- `vidsByQID` - this can be populated using `questionsByQID`
- `zones` - create an array of `null`s
- `showZoneTitles: false`
- `maxScore` -  copy from `nQuestions`
- `gradingDates` - from `finishDate` if it exists, otherwise `[]`

It looks like the right place to put this is near the end of `RetryExamServer.updateTInstance`, with a check for `tInstance.questionsByQID === undefined`

Does that seem right?

**Comment by mwest1066** [comment]
Sounds exactly right. `updateTInstance()` is used exactly for these sorts of on-the-fly schema changes. Testing this is always a bit of a pain because we need to create tests with the old code, then run with the new code and check the updates are happening correctly, etc.

**Comment by mwest1066** [comment]
Implemented in v2
