### ISSUE TITLE
Instructor close all issues button no longer working

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1995]
The "Close all issues" button throws a Not Found error and doesn't remove the open issues. This is new with the recent deploy.

**Comment by tbretl** [comment]
Hmm, @trombonekenny I can't reproduce this either locally or on prod. Can you be more specific?

**Comment by trombonekenny** [comment]
I noticed it on this page in prod: https://prairielearn.engr.illinois.edu/pl/course/149/course_admin/issues

**Comment by mwest1066** [comment]
I also get the error when clicking "Close all issues" on the page that Dave linked above. From the logs the error happens on the POST request to `/pl/course/149/course_admin/issues`. It looks like we are dropping through the check at https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorIssues/instructorIssues.js#L146

I believe the problem is that we are at the course level, so we haven't set `has_instructor_edit` (these are only set for course instances).
