### ISSUE TITLE
Assessment student instance log bulk download

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2071]
The instructor assessment instance page, where you can view the detailed log of the student's engagement with the assessment, has a CSV download link. Can we aggregate that into something that downloads all of those per-assessment?

Either on the Downloads tab for the assessment or via the API?

**Comment by mwest1066** [comment]
Was someone wanting this in particular? Any specific use case, or just generally wanting the data?

I like the suggestion of providing this via the API. It wouldn't be hard to add the other log output objects. The API scales really well because we can return the objects one by one and let the caller walk the tree. This avoids the problem of producing a giant CSV file.

**Comment by mwest1066** [comment]
Implemented in #3129
