### ISSUE TITLE
Any JS included in question.html is executed four times

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#211]
This, in particular, is an issue if you have any event listeners which in turn modify the DOM because it's executed 4x.

**Comment by mwest1066** [comment]
While I agree that it's suboptimal for question.html to be repeatedly re-rendered, I think this is an efficiency issue rather than a correctness issue. That is, the code assumes that question rendering is idempotent, and in fact needs to re-render the question on certain data change events. Because of the way Backbone works (in particular, it's inability to batch change events) this re-rendering sometimes occurs more often than one would expect.

There are two solutions to this, I think. The best solution is to switch to React, but we aren't going to do that immediately. The second solution is to not put JS in `question.html`, which I think is the correct solution. Instead all JS should go into `client.js`, which is exactly where it should live. If you need to run JS after the templates have rendered then listen for the `renderFinished` on the SimpleClient object.

I know that the documentation for advanced, JS-heavy questions is not very detailed (to put it mildly). I suggest meeting to talk about what you are trying to accomplish so we can figure out how to achieve it in the best way in PL. I'm free to meet this week or next if you are around?

**Comment by tnip** [comment]
From experimentation, it looks like `renderFinished` is actually not an event that's fired (i.e. detectable) in `client.js`. It also seems like any modifications to make it fire makes it fire three/four times?

**Comment by mwest1066** [comment]
Fixed in v3 questions.
