### ISSUE TITLE
Add "Request a New Course Button"

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2172]
Procedure now for spinning up a new course is to request one from Matt or one of PL core's members via e-mail. 

It would likely be more ideal to adopt the course request process similar to compass2g/canvas by creating a campus web-form that can validate faculty affiliation level and process the course every evening.

**Comment by trombonekenny** [comment]
This issue seems to be around the whole workflow for setting up courses (repos, PL database, etc.)

As a needed but intermediate step, having a button in the PL docker devMode to create a new course (that is copying in a template to `/course/infoCourse.json` and doing a Load from Disk) so that instructors can get started entirely from inside PL would be very helpful. There's lots of in-the-browser editing possible, but you need a `/course/infoCourse.json` to exist first to get in the door.

**Comment by nicknytko** [comment]
resolved in #2673
