### ISSUE TITLE
Documentation note on distractors

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#2194]
Consider the following prompt:

```html
If $a = {{params.a}}$ and $b = {{params.b}}$, then what is $a$ multiplied by $b$? 
```

The correct answer would be: `a * b`.

When generating distractors, the following might be reasonable. 

```python
    data['params']['wrong_answer1'] = a * (b - 1)
    data['params']['wrong_answer2'] = b - a
    data['params']['wrong_answer3'] = a + b
```

That said, the distractor construction relies upon the range of values generated for `a` and `b`. In this case, if we let `a`, `b` be a values in [1.1, 5] and [5.1, 10] respectively, then we'll have a problem with the `a+b` distractor and the true answer. 

In particular, if `a = 1.2` and `b = 6`, then `a * b = 7.2 = a + b`. So, `wrong_answer3` would be equivalent to the correct answer. It's safer to generate distractors here with `(a - 1) * b` and `(a + 1) * b` or something like that, which must be distinct from `a * b`.

(Last paragraph taken from @mwest1066 during review https://github.com/PrairieLearn/PrairieLearn/pull/2173#discussion_r395934374 )

**Comment by mwest1066** [comment]
To clarify this example a bit more, the original code generated the random parameters with:
```
a = round(random.uniform(1.1, 5), 1)
b = random.randint(6, 11)
```

That is, `a` has resolution of 0.1, so there is a 1/39 chance of getting `a = 1.2`. There is also a 1/6 chance of getting `b = 6`, so overall there is a 1/234 chance of hitting this case where we generate a distractor that's the same as the correct answer.

I love this example because 1/234 is rare enough that you probably won't find it in testing, but common enough that a student will hit it in a large class.

**Comment by mfsilva22** [comment]
I can add a tutorial/question that has this example. I was wondering if we can also mention that we can try to

**Comment by eliotwrobson** [comment]
I think this issue overlaps with #1228 and can be closed when that fix gets merged + documented.
