### ISSUE TITLE
Catch errors explicitly from server.py and send stdout via websocket

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2272]
At the moment we communicate server.py exceptions by printing them to stdout and interpreting anything on stdout as an error. Instead it would be awesome to explicitly catch errors and communicate them via the JSON output.

This would allow us to treat stdout output as not-an-error and display it on the question page via a websocket. This would allow instructors to put `print()` statements in `server.py` and see the output directly on the question page.

**Comment by eliotwrobson** [comment]
@mwest1066 I'm pretty sure this already happens? Looks like this can be closed.

**Comment by mwest1066** [comment]
I think we never implemented this. At the moment we still interpret anything on `stdout` as an error, which means it's slightly annoying to debug questions. I'd be happy to close this issue anyway because we should really rethink our debugging strategy in a broader sense than just this issue.

**Comment by eliotwrobson** [comment]
Ahh, that makes sense, I mentioned something related to this issue here: https://github.com/PrairieLearn/PrairieLearn/issues/7337

But I'm very much in agreement that some change to the debugging / error handling strategy would be great to have. Maybe worth making a discussion item about it rather than having a few loose issues running around? Closing.

**Comment by mwest1066** [comment]
> But I'm very much in agreement that some change to the debugging / error handling strategy would be great to have. Maybe worth making a discussion item about it rather than having a few loose issues running around?

This would be great!
