### ISSUE TITLE
Able to sync despite Shibboleth logout

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#235]
I'm apparently able to do a course sync even though Shibboleth's logged me out - which I don't believe is intended behaviour?

**Comment by mwest1066** [comment]
Thanks for the alert. In fact it's not really a bug, or at least not an unknown bug, because we've been caching login credentials in a cookie since 01e85b78d75ed9e6fcf9247a1b15499084f611b7. This is safe because the cached credential is just a hash, but unsafe in that we don't currently do credential timeout server-side. I added issue #237 to fix this.
