### ISSUE TITLE
Store 'graded' flag for submissions in the database

### ISSUE THREAD

**Issue by rbessick5** [PrairieLearn/PrairieLearn#270]
All submissions are 'scored' (marked correct/incorrect) at the time they are saved, but whether a submission has been graded is tracked by the tInstance (and only for the most current submission per each question in that tInstance). The graded status of a past submission is needed to fully address #255 and #263 .

We should do the following:
- Add a 'graded' flag to each submission (default to false) when it is created
- Provide a PATCH operation (like for tInstances) to update this flag when a submission is graded.

We can probably continue storing the graded status in tInstances as is (that is, for the most recent sid per qid) as long as this information is well-synced with the submissions themselves.

**Comment by mwest1066** [comment]
At the moment we are doing something pretty horrible in the DB that will affect this issue. Namely, submissions are stored in two different ways. First, they are stored in the `submissions` collection in the DB, which is the proper way to store them. This is a write-only log of all submissions. These submission objects include grading information (because the server grades them as they are submitted), but we don't update them later with information about test gradings or anything like that.

The second way that submissions are stored is directly in the tInstance for RetryExam tests. This is a horrible hack. Only the most recent submission for each QID is stored (in the `submissionsByQid` property of the tInstance), and these are updated with grading information, etc. Because we only store the most recent submission for each QID, however, we can't use this to display history.

Apart from the fact that this two-fold storage scheme interferes with resolving this issue, it's also incoherent to be double-storing data in the DB in two different forms.

To fix this there are three different stages:
* First, we could simply store a history of submissions inside the tInstance. This would involve changing `tInstance.submissionsByQid` from a mapping `QID -> submission` to a mapping `QID -> list of submissions` where we push new submissions onto the end of the list. This would allow us to resolve the current issue.
* Second, we should stop storing submissions in the tInstance in any way, and instead always access them from the `submissions` collection in the DB. This will require two changes to the way that the main `server.js` calls `RetryExamTestServer.js` functions: (1) from inside `RetryExamTestServer.js` we will need access to the DB, and (2) we will need to change functions like `RetryExamTestServer.grade()` to be async. We might also need to add more indexes to the `submissions` collection to enable efficient queries for submissions by QIID or something,
* Third, we should switch to a SQL DB (#245), which would make all of this better.

**Comment by mwest1066** [comment]
Fixed in v2
