### ISSUE TITLE
Log question view timestamps

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#271]
Would be great for auditing purposes, as well as for gauging how long/difficult questions are relative to their point value for future semesters.

**Comment by mwest1066** [comment]
Needed for #253.

At the moment we technically have this information because it's in the `accesses` DB collection, but it's in a horrible format.

We should add a new collection to the DB called `qAccesses` or something (for "question accesses") and log information in a much more structured form. For example, in `app.get("/qInstances/:qiid/:filename")` we should record accesses to `client.js` and store a `qAccesses` record like:

    {
        "timestamp", ...,
        "qid": ...,
        "tid": ...,
        "tiid": ....,
        "qiid": ...,
        "authUID": ...,
        "userUID": ...,
        "mode": ...,
        "authRole": ...,
        "userRole": ...,
    }

**Comment by mwest1066** [comment]
Replaced by #409
