### ISSUE TITLE
Workspace hosts should pre-cache docker images before on startup

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3014]
This is similar to what the external graders do

Upon startup, grab some of the most recently used workspace images and pre-cache them.  As a host, we should only mark ourselves as ready after this pre-caching step.

**Comment by mwest1066** [comment]
My only concern with this is that it will slow down the launching of new hosts in times when we are under heavy load. For example, say there have been 5 images in recent use, and then class X suddenly has hundreds of people using the same workspace. If we pre-cache, then every host will download all 5 images before accepting any new workspaces, which will leave many students from class X stuck in the "waiting for host" stage. On the other hand, if we use the current system (no pre-caching) then the hosts will come up faster and immediately accept workspaces for class X, and the students will see the loading percentage as these hosts pull just that one required image.

I think the current system (no pre-cache) will actually get more students into workspaces faster (no need to download the other 5 images before useful work gets done) and will also show them a percentage loading, which is a much nicer UI than just "waiting".

This is all different in the case of external graders, which are optimized for short jobs. In that case I think it does make sense to pre-cache, because a new grader without a cached image takes a long time to process a job, and in that time it's very likely that another grader will become free and can handle the job. For workspaces it's very unlikely that another host will become free while we are waiting, because we assume workspaces are long-lived. At least that's my intuition (this is a neat queuing problem that ideally needs some serious analysis, data, and simulations).

**Comment by tdy** [comment]
Is pre-caching done with dockerode? If so, we could move the percentage updates into `Waiting for host`?

**Comment by tdy** [comment]
Though that still doesn't fix the issue of everyone being blocked on `Waiting for host`.

**Comment by mwest1066** [comment]
Right, workspaces that are waiting for a host can't display any useful percentage from a host that is doing pre-caching, because they aren't assigned to a host yet (which host would they show the percentage from?).

**Comment by tdy** [comment]
Ah, right 👍

**Comment by nicknytko** [comment]
So, once the AWS ECR stuff is in we shouldn't actually need to do this?

**Comment by mwest1066** [comment]
> So, once the AWS ECR stuff is in we shouldn't actually need to do this?

Yep, I think that's correct. Speeding up the pulls (with ECR) should take care of this.
