### ISSUE TITLE
MathJax SVG rendering does not display correctly on low-dpi displays

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3086]
Reported by Sarka. Thin lines in math SVGs vanish. For example, some of the lines in `+` signs are missing, especially in fractions.

@echuber2 reports this is a known issue in Chrome: https://techcommunity.microsoft.com/t5/discussions/svg-antialiasing-issues/m-p/788141

**Comment by echuber2** [comment]
Also, the issue doesn't seem to happen with Chrome/Chromium on Mac or Linux, only Windows. If someone has time, it would be nice to get confirmation if this happens with Windows+Firefox too, or only Windows+Chrome.

I'm not sure what can be done about this if the issue is browser SVG rendering. On a previous project, I was able to fix a similar error that was peculiar to Mac/Safari by increasing the `viewBox` dimensions, which also required adjust all the local user-space coordinates in the SVG object. For some reason this improved rendering quality (although it shouldn't have; it suggests Safari was determining precision by a fixed number of places after the decimal, rather than by significant digits).

If something like that won't work, we may need to rasterize the rendered MathJax at 2x or 4x and display the image in its place, to achieve better superscaled antialiasing. We should be able to detect that the user has Windows with client-side JS as well as not-Firefox, and we can also try to detect the standard font height in pixels.
