### ISSUE TITLE
Dropdown element does not support latex

### ISSUE THREAD

**Issue by tdy** [PrairieLearn/PrairieLearn#3145]
`pl-dropdown` currently uses html `<select>`/`<option>`, which is not supported by mathjax.

One possible workaround:

> @nicknytko 2:43 PM
> we could rework the dropdown to use the bootstrap one that is a bunch of `<a>`s and a `<div>`

See **https://getbootstrap.com/docs/4.5/components/dropdowns/**

```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```

**Comment by andrewstec** [comment]
CSS is insufficient in the area of styling Select Dropdown Options. Where there is limited success in styling, it cannot be guaranteed by cross-browser support.

I do not know much about Mathjax, but what are the requirements for Mathjax to work with the element? What does it have to accomplish?

Cinda has experienced a similar issue recently involving simple styling of the font. The lack of CSS support means on the Select Dropdown Options means that the font will not change to something that is friendlier for programming languages.

**Comment by nicknytko** [comment]
> CSS is insufficient in the area of styling Select Dropdown Options. Where there is limited success in styling, it cannot be guaranteed by cross-browser support.
> 
> I do not know much about Mathjax, but what are the requirements for Mathjax to work with the element? What does it have to accomplish?
> 
> Cinda has experienced a similar issue recently involving simple styling of the font. The lack of CSS support means that the font will not change to something that is friendlier for programming languages.

MathJax will insert rendered math as SVG elements on the page, so I think we need some HTML element that will render children.  I think the `<option>` will only display plain text (https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element), which is why I was suggesting we check out the bootstrap dropdowns as those create a fake "dropdown" out of a bunch of `div` tags.

**Comment by andrewstec** [comment]
I think that your `DIV` and `A` approach sounds perfect then.

**Comment by Surg-Dev** [comment]
Is there anyone else looking into this?

I did a bit of testing, on top of all the required PL js for dropdowns, bootstrap needs additional code to update the text to the selected option, This may not always have intended results, since I'm new to webdev, I'm not really sure where that needs to get placed in the PL rendering pipeline.

**Comment by nwalters512** [comment]
A note for anyone looking at this in the future: you'll need to ensure that any replacement to the native `<select>` element is equally as accessible. [Bootstrap's docs](https://getbootstrap.com/docs/4.5/components/dropdowns/#accessibility) will help point you in the right direction, but just adding `aria-role=...` will not be sufficient.
