### ISSUE TITLE
Markdown previewer in pl-file-editor is vulnerable to XSS

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3194]
Previewer allows any HTML code to execute. Code like `<img src=x onerror="alert('hi')">` triggers arbitrary javascript to run. Although in most cases this only causes minor issues to the student themselves, it has the potential to cause bigger problems in cases of social engineering, such as asking an instructor to open the student view of a submission.

The previewer should sanitize the input before showing it, or block any invalid HTML tag (whitelist only).

**Comment by echuber2** [comment]
What would invalid tags consist of, `style` (perhaps) and `script`? I think you may need to preparse the html and look at individual attributes too, such as `onerror` there.

If some instructor _wants_ to use the HTML preview mode to let people mess with styles, maybe it would make sense to render the preview into a sub-document instead of the main page document.

**Comment by jonatanschroeder** [comment]
I'll use the `xss` library. Trying to come up with all possible combinations is probably unsafe.

**Comment by echuber2** [comment]
To restrict styles to the preview, I think we could render the preview as a shadow DOM. https://css-tricks.com/playing-shadow-dom/

**Comment by jonatanschroeder** [comment]
Fixed in PR #3195 .
