### ISSUE TITLE
Instructors still can't see stacktraces on broken question variants

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3247]
On slack the other day we were running into the issue where an "Error creating question variant" message was being generated but the instructor couldn't see any stack trace or relevant data.  They were marked as instructor for the course instance and owner of the course, so in theory they should have been able to see it.

In case it's relevant, the stack trace that was generated:
```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 167, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 113, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-multiple-choice/pl-multiple-choice.py", line 195, in prepare
    raise Exception('duplicate params variable name: %s' % name)
Exception: duplicate params variable name: iso
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 179, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

This ended up being an error in the `question.html`.

**Comment by tdy** [comment]
Is this an authz bug?

* [Course question preview](https://www.prairielearn.org/pl/course/108/question/7972699/preview) -> `Dev User`
* [Course **instance** question preview](https://www.prairielearn.org/pl/course_instance/4970/instructor/question/7972699/preview) -> `Dev User (Instructor)`

I'm guessing instructors can actually see instance preview backtraces right now, but that course preview backtraces are hidden due to `authz_data.has_instructor_view`:

https://github.com/PrairieLearn/PrairieLearn/blob/efa2734d181077c62f93842f000917850fd61f27/pages/partials/question.ejs#L30
