### ISSUE TITLE
Hint text for "Available points" incorrect

### ISSUE THREAD

**Issue by bowmnath** [PrairieLearn/PrairieLearn#3377]
I believe the grading formula shown to students in the PrairieLearn help text is incorrect.  Here are some images for an example exam problem with a `[10, 7, 2]` grading scheme where I scored `7.5/10` on the first attempt.  (The `2` part in the grading scheme won't be relevant for any of this.)

![example-score](https://user-images.githubusercontent.com/57008120/97068915-d012ba80-1599-11eb-881a-f7797199a0de.png)

The available points are 7/10 of the 2.5 that I missed, so 1.75 points.  Those additional points should scale linearly from 0 to 1.75 as my score on the next attempt goes from 75 to 100.  So, the formula is 

1.75 * (score - 75)/25.

A quick sanity check shows that this is linear, that a score of 75 nets me 0 points, and a score of 100 nets me 1.75 points, so the formula should be ok.

The formula shown in PL is given in the image below (last box).

![incorrect-formula](https://user-images.githubusercontent.com/57008120/97068897-9f328580-1599-11eb-9818-5ec7ee7b3ff6.png)

Note that the formula is dividing by 100 instead of 25.

A similar formula that is equivalent to the correct formula above is

7*(score - 75)/100.

The difference between this and the PL formula is that the PL one double counted a multiplication by 0.25.

Of the two correct formula given here, the first one (or the slight variant 1.75 * (score - 75)/(100 - 75))
* is more natural to me as a way to understand what is going on, and
* involves the number 1.75, which is what they are shown in "Available points" and what they care about.

But, I think the second one looks cleaner and easier to compute because it involves integers and a division by 100.

If I am correct about the formulas involved, I would suggest we pick one and update the hint.

**Comment by mwest1066** [comment]
Good catch!

For context, here's the code that compute the new points: https://github.com/PrairieLearn/PrairieLearn/blob/7c9f93885ed39ad2958beff15434ba79aabb889a/sprocs/instance_questions_points_exam.sql#L35

It's using the equivalent of `7*(score - 75)/100` (it doesn't actually do the `/100` because internally the score takes values in the range [0,1]).

It seems to me that any of your three proposed fixes would be fine. It's not really clear to me which one is the least confusing! I don't think any aspect of this scoring system is really simple 😄 -- but I do think it's the right scoring system to use.

The way I sometime explain this is that we take the points list (e.g., `[10, 7, 2]`) and the list of submission percentage scores (e.g., `[75, 50, 90]`) and then do:

1. Calculate the positive incremental percentage scores, e.g., `[75, 0, 15]`
2. The points for each submission are the positive incremental percentage scores for that submission multiplied by the corresponding points, e.g., `[10*75%, 7*0%, 2*15%] = [7.5, 0, 0.3]`
3. Total points are the sum of the points for each submission, e.g., `7.5 + 0 + 0.3 = 7.8`

Some properties of this scoring system are:
1. The total points can never decrease.
2. If a new submission improves over the previously-best submission, then additional points will be awarded.
3. Better answers earlier (higher submission scores for earlier attempts) cannot result in lower points, so there is always an incentive to give the best possible answer as soon as possible.

Following on from the above, I guess this would suggest changing the help text to show `7*(score-75)/100`. Or maybe `7*(score% - 75%)`. This could be said in words as "7 points multiplied by your incremental percentage score (additional score over 75%)".

But I'm very open to other ways of explaining this! I haven't done any user testing to see which formulas/explanations are the most readily understood by students/faculty. Certainly it's a good idea to make the help text be correct 😄 and also add a detailed explanation for instructors to the documentation!

**Comment by bowmnath** [comment]
I only noticed because I was hoping the help text would help me figure it out so I could write the description :sweat_smile: 

Thanks for the detailed explanation.  I'm still trying out different descriptions for the documentation.  I suppose I'll post any suggestions for that as a separate issue.

In the meantime, I would vote for `7*(score-75)/100` along with your proposed wording.  If you agree and want me to make the change, just let me know.  Or, we can wait until you and Mariana and whoever else can weigh in on the doc changes in case that affects what we do here.

**Comment by mwest1066** [comment]
> In the meantime, I would vote for `7*(score-75)/100` along with your proposed wording. If you agree and want me to make the change, just let me know. Or, we can wait until you and Mariana and whoever else can weigh in on the doc changes in case that affects what we do here.

PRs are always welcome! 😄

**Comment by mwest1066** [comment]
> > In the meantime, I would vote for `7*(score-75)/100` along with your proposed wording. If you agree and want me to make the change, just let me know. Or, we can wait until you and Mariana and whoever else can weigh in on the doc changes in case that affects what we do here.
> 
> PRs are always welcome! 😄

And in case this wasn't clear, I'd love for you to make the change! 😄

**Comment by bowmnath** [comment]
It was indeed clear -- thanks for the reminder! :smile: 

I found the page that needs editing (`pages/partials/examQuestionAvailablePointsInfo.ejs`).  However, I think that the variable I need is not currently used there, and I'm not sure how to find it.  The `points_list` has the actual points available, whereas I need the original `[10, 7, 2]` values to print the formula.

Do you know what variable I should access to get that?

**Comment by mwest1066** [comment]
The include chain goes:

https://github.com/PrairieLearn/PrairieLearn/blob/a712149711a5726ee5228d5ac1021c452b549b20/pages/partials/examQuestionAvailablePoints.ejs#L22

https://github.com/PrairieLearn/PrairieLearn/blob/a712149711a5726ee5228d5ac1021c452b549b20/pages/partials/questionScorePanel.ejs#L17

You can see above that it's accessing `instance_question.points_list`. I think the `[10, 7, 2]` values that you want are in `instance_questions.points_list_original`: https://github.com/PrairieLearn/PrairieLearn/blob/a712149711a5726ee5228d5ac1021c452b549b20/database/tables/instance_questions.pg#L25

**Comment by bowmnath** [comment]
That was certainly a learning experience -- thanks for your patience, and for showing me the include chain.  I would not have figured out where those variables were coming from.
