### ISSUE TITLE
Logging partial submissions on calculation-type problems

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#361]
We have a custom parser for a certain type of question. We'd like to have some build-up on a single "question" page where with each field being checked, immediate hints and feedback can be received, while partial credit is awarded. Right now this is working except we're not sure how to store the complete log of partial responses for a particular instance. The final POST done by the SimpleClient only logs the final submittedAnswer value from the input field in our CSV. What I think I need to do is build a record of the responses using the other POST features of the client API or else do something custom in our parser to log responses in a separate way. Are there any examples we can see where something like this has been implemented?

**Comment by echuber2** [comment]
A simple workaround I'd considered is building a local history of partial answers and replacing the input field with that log before the final POST, but of course this is a poor solution as the submission history can be forged on the client side.

**Comment by mwest1066** [comment]
Could you describe in more detail (perhaps with an example) what type of question you are trying to write here? PL discourages long scripted questions in favor of sequences of short questions, each of which can stand on its own. This is done because it greatly simplifies analytics and also enables question re-use and flexibility. Sometimes it might be worth sacrificing these benefits, but one should think about this carefully, and I'd like to understand your situation better.

Also, I generally discourage direct API access from within questions. It's likely that there are better ways to achieve your goals, or we should enhance the question interface to enable your type of question.

**Comment by echuber2** [comment]
This particular example involves evaluating the buildup of closures using a handwritten map notation for CS 421. It's important to demonstrate the buildup over a sequence of binding events, and we'd rather not force the student to attempt this all at once as it makes it harder to award partial credit in stages, and also harder to get hints about how to answer the question correctly after an initial wrong answer. I'd thought of putting each of these partial prompts as a completely separate question, but then we'd need to ensure that they are chosen in a particular order; that is, one sequence of questions should be randomly selected for a user, and then it must display each question in that sequence.

**Comment by mwest1066** [comment]
Ok, I think I understand the type of question you are writing.

Are these strictly "learning" type questions (for formative assessment), or might they be used on tests/exams as well?

I'm not quite clear on the partial credit scheme that you are wanting to use. Is the goal to award partial credit for having answered only some pieces of the question correctly?

**Comment by echuber2** [comment]
These question types are intended for both formative practice (or as a homework assignment) and possibly to appear as an exam question at the CBTF lab. Our scheme for partial credit would be something along these lines: answering a prompt correctly (as determined by our parser) gives full credit, whereas requiring multiple attempts (possibly with hints) reduces the amount of credit. Our intention for now as to dump the complete log of attempted responses and run a grading algorithm on the logs after the fact, possibly with hand-correction for exceptional cases.

**Comment by mwest1066** [comment]
Does this mean that you want to award points per sub-question?

Also, re-reading your earlier posts, I want to make sure that you are aware that PL is storing all submissions to each question (every time the student clicks "submit" it is stored) and these are all available by default from the `XXX_all_submissions.csv` file on the test Admin page. This might be the information that you want?

In any case, it would clearly be better to have the grading being done online rather than post-hoc. We should work to make that happen. I'm always happy to take PRs for changes to PL itself, of course!

**Comment by echuber2** [comment]
The all_submissions.csv file for us contains a submittedAnswer column that only records the final value entered in the input form field. Because each question page is intended to ask several followup questions, the current scripts we have are dynamically editing the page content to reveal more information and prompt a new question by overwriting the field of the questionData object. The fact that we are reusing the same input field as this process unfolds seems to be the issue, as only one submittedAnswer value seems to be POSTed in the end. Our scripts may be going about this in the entirely wrong way I suppose.

**Comment by mwest1066** [comment]
Oh yes, please don't overwrite properties in the submission object. This will definitely confuse PL. Can you just submit by adding properties as you go?

But honestly, it sounds a bit like you are trying to do too much from javascript running inside the question. It would probably be easier to adapt PL itself to support what you are trying to do, rather than hacking around PL from inside a question.

I didn't realize that you want all of this to be dynamic, revealing more information to students as they go. Does this mean that a "question" is really a sequence of questions? If so, I think it would be much simpler to actually use separate questions in PL to achieve this. This may require some changes to PL of course, but that's fine.

**Comment by echuber2** [comment]
I'm not sure what you mean by adding properties as we go. Adding properties to which object, the questionData? Would that cause the submittedAnswer to gain fields as well somehow? Yes, we intend it to be a sequence of related questions. We could have each one on a separate page as long as there was some way to guarantee that they would be shown in the correct sequence, and that the sequence itself would be randomly chosen from a set of alternative sequences.

**Comment by mwest1066** [comment]
Closing this issue after our in-person discussion. Please re-open or start a new issue if there are remaining questions.
