### ISSUE TITLE
Create another column in the Students Page (tab) 

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#3658]
Current page for an individual assessment:

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/12501485/103581187-63b51100-4e90-11eb-8511-3408f403e86f.png">

I propose we create another column (maybe the third column) that has the header "Details" and the following text for each row entry:

<short_assessment_name>  + (<assessment_instance_number>) + for + <user_uid>

For the example above, the entry would be `HW6(1) for mfsilva@illinois.edu`.

This text would have a link that points to the same page when the button "Details" is clicked. The columns "Details" could then be removed.

For a group assessment, the row entry would be 

<short_assessment_name>  + (<assessment_instance_number>) + for + <name_entry>

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/12501485/103582152-2b163700-4e92-11eb-9070-7774d23c7b4e.png">

For the example above,  `L7(1) for Mari`.

____

In the future, we would also add a link to the column `UID`, which would direct to a page that contains informations about that student (assessments, assessment summary and statistics, etc). This page does not exist yet (another PR!), but once we have this page,  we should add a link to it in all occurrences of UID (the above example, the gradebook, ...)

**Comment by jonatanschroeder** [comment]
I like the idea of moving the Details button to a link, but I think this could replace the Instance column instead of adding a new column. Also the text could use the same abbreviated format for instances (e.g., `L7.1`) instead of brackets.

Any reason why the UID or group name would need to be repeated?

**Comment by mfsilva22** [comment]
Agree with you that we could have this information replacing the instance column, but I think @mwest1066  didn't want to remove that column? 

And yes, the notation L16.1 is better :)

We want to keep the user id, because this is consistent with what the page is: assessment information for a given student. The same text that appears in the column as link should also appear on top of the actual page (banner). It will hopefully make the naming of the page more clear and consistent, during conversations, slack, office hours and documentation

**Comment by mwest1066** [comment]
I'm happy to remove the "Instance" column if we use notation like L16#1. The main reason I'm normally worried about removing columns is because we lose the ability to sort on that column. For "Instance" this won't matter because sorting on the new column will have essentially the same effect.

I'm not sure whether we should have:
```
L16#2 for mwest@illinois.edu       <== OPTION (1)
L16 for mwest@illinois.edu (#2)    <== OPTION (2)
```

I prefer the look of option (1), but it has the disadvantage that sorting by this column would not do the obvious thing of grouping all the assessments for one user together. I suggest:

* We use option (2),  but we only write the instance number suffix (like `(#2)`) if `assessments.multiple_instance = true` or `assessment_instances.number > 1`.

This scheme will avoid adding the instance number unless it's needed, and will still make sorting work as expected.

**Comment by mwest1066** [comment]
I'm thinking that this new column is the "name" of the object described in each row and for that reason I suggest:

1. The new column should be the first column.
2. The new column should have no header. This would match the Assessments page, where the "name" of each row is in the first column and doesn't have a header:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/875833/103795956-40af6c00-500c-11eb-9d75-0837616b4bf0.png">

An alternative would be to use a header like "Student assessment" that describes what the name refers to.

**Comment by mwest1066** [comment]
It would also be great to strip `@illinois.edu` from UIDs in the new column. We could do this by stripping the domain for any users who are in the same institution as the course, while still keeping the domain for any "foreign" users.

**Comment by jonatanschroeder** [comment]
@mwest1066 @mfsilva22 is this what you have in mind? The instance number only shows if the number is > 1 or if the assessment has multiple instances. For group work, the UID is replaced with group name. Sorting by this column uses the order UID, user ID, instance number, AI ID (or group name, group ID, instance number, AI ID for group work). Note that the Details column has been removed. The instance number has been hidden by default (unless the assessment is multiple instance, then it's shown by default), but still can be shown by selecting the column in the dropdown in the top right. The UID or group name are also hidden by default, since the info is in the instance.

![image](https://user-images.githubusercontent.com/1004907/127057892-0166b684-7e80-4d9c-88e0-235af4c4c550.png)

I haven't yet stripped the institution from the UID. My guess is that this is what `authn_institution.uid_regexp` can be used for, but I don't have access to a real (non-dev) case of what this variable should have in production, since dev sets this value to `null`. @mwest1066 any guidance here?

**Comment by mwest1066** [comment]
Looks awesome! I love how we can easily control sort order.

**Comment by jonatanschroeder** [comment]
> I haven't yet stripped the institution from the UID. My guess is that this is what `authn_institution.uid_regexp` can be used for, but I don't have access to a real (non-dev) case of what this variable should have in production, since dev sets this value to `null`. @mwest1066 any guidance here?
> 

Do you still want this?

**Comment by mwest1066** [comment]
> > I haven't yet stripped the institution from the UID. My guess is that this is what `authn_institution.uid_regexp` can be used for, but I don't have access to a real (non-dev) case of what this variable should have in production, since dev sets this value to `null`. @mwest1066 any guidance here?
> 
> Do you still want this?

Good question. What do you think? I'm a bit torn. I like saving space when you have many students who are all the same, but I also like the clarity of listing the full UID.

If you want to try it, `authn_institution.uid_regexp` is equal to `@illinois\.edu$` for Illinois and `@ubc\.ca$` for UBC. Sometimes they are more complex, such as `@(mail\.|)gvsu\.edu$` for GVSU.

**Comment by jonatanschroeder** [comment]
> > > I haven't yet stripped the institution from the UID. My guess is that this is what `authn_institution.uid_regexp` can be used for, but I don't have access to a real (non-dev) case of what this variable should have in production, since dev sets this value to `null`. @mwest1066 any guidance here?
> > 
> > Do you still want this?
> 
> Good question. What do you think? I'm a bit torn. I like saving space when you have many students who are all the same, but I also like the clarity of listing the full UID.

I can try adding an option, similar to auto refresh.

> 
> If you want to try it, `authn_institution.uid_regexp` is equal to `@illinois\.edu$` for Illinois and `@ubc\.ca$` for UBC. Sometimes they are more complex, such as `@(mail\.|)gvsu\.edu$` for GVSU.

This sounds like an easy regexp to remove...

**Comment by mwest1066** [comment]
> I can try adding an option, similar to auto refresh.

The more I think about it, the more I'm worried that we would need to implement this globally within PL for consistency. I'm thinking that this is a lot of work for little gain at this point. Maybe best to just keep it as an idea for now?

**Comment by jonatanschroeder** [comment]
Sure, maybe separate issue?

**Comment by mwest1066** [comment]
> Sure, maybe separate issue?

Absolutely!
