### ISSUE TITLE
Manual Grading: Grading Access Locks

### ISSUE THREAD

**Issue by bevansm** [PrairieLearn/PrairieLearn#3786]
As mentioned in #3720, two users can unwittingly grade the same question at the same time. @andrewstec has started most of the work on this, but we need to give more attention to the SQL procs we're using.

- [ ] Add a flag to submissions to indicate if the submission is currently being graded
- [ ] Unmark questions that have gone ungraded for a long period of time
- [ ] Display a notification to the user that someone else has already started editing the question
- [ ] Handle the case when another user has graded the question before you submit a grade

**Comment by jonatanschroeder** [comment]
I'm adding this here so it isn't lost: we need a way to keep track of stats per grader (e.g., how many submissions did each grader grade for a specific question). This is both for the grader (e.g., they were assigned to grade 200 submissions, so they need to keep track of how many they have left) and the instructors (who has completed their allotted marking duties, who hasn't).

**Comment by jonatanschroeder** [comment]
Alternative: assign a list of submissions to a specific grader, then have a way for the grader to see the submissions they have been tasked with.

**Comment by mwest1066** [comment]
I would be inclined to add a per-assessment "manual grading stats" page that shows the results of a query over grading jobs to show how many questions each grader grade. This is robust and doesn't require storing any new data. Unless we need this live, somehow?

I like the way we've been going where everyone sees everything that needs to be graded. An assignment system feels like a lot of additional UI for minimal benefit.

**Comment by jonatanschroeder** [comment]
Sounds good. We don't need this live, refreshing occasionally is fine.

**Comment by jonatanschroeder** [comment]
To make sure this is written somewhere, about the case when another user has graded the question: this needs to be done in some atomic fashion where the update would fail if the state since the question was loaded has changed. In other words, if the grade/feedback/??? has changed since the question was loaded, the grader will be presented with both the current grade/feedback and the grade/feedback that was submitted, as well as info like who graded it and when. The grade then has a choice to either overwrite the grade (potentially with further modification to account for feedback that could be informed by the other grader's comments), or keep the saved grade. When overwriting the grade the same check should happen again.

A similar process should also take place if a newer submission is found upon submitting a grade.

**Comment by jonatanschroeder** [comment]
Marking these as done. Conflict management is done in #5547, preliminary stats are done in #5670.
