### ISSUE TITLE
Is the student identity passed to the external grader?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#3822]
Do we pass anything identifiable about the student to the external graders? Steve Lumetta was asking last fall for ECE 120 labs, but I don't have the full context.

**Comment by mwest1066** [comment]
No, we do not pass student identity to the external grader (or to the internal grader). While it would be technically easy to pass identity information, we've been very hesitant to do so because of student privacy concerns. If someone has a good use case for this then we'd be open to adding identity data as an option.

**Comment by nwalters512** [comment]
We've discussed this a number of times over the years and haven't yet heard a compelling use case for it. I'm going to close this. If someone is looking for this functionality, please open a new issue with a detailed description of your use case.
