### ISSUE TITLE
Upgrade code-server to 3.9.1

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#4036]
Can we upgrade our version of VS code-server used in the workspaces? The pinned version (#3856) seems out of date with ms-python extensions relating to the debugger not working.

https://github.com/cdr/code-server/issues/2341 seems to suggest that the newest versions of VS Code and the python extension might fix it.

cc @ireneog

**Comment by echuber2** [comment]
Any reason not to use 3.10.2?

**Comment by echuber2** [comment]
I'm experimenting with this in my modified image (#3170) and it seems okay so far.

**Comment by nwalters512** [comment]
I think it's time to do this. @trombonekenny do you have the bandwidth to test the latest image and submit a PR if it works?

**Comment by echuber2** [comment]
So, I do have a version of the workspace that's more updated that I could PR, but it's based on the more recent v4.x flavor. After 3, they broke compatibility with Microsoft's addon marketplace, so you have to manually obtain the vsix files you want and bake them into a derived workspace from then on (*unless* the same extensions are also available in the open-vsx marketplace). I did some other quality of life stuff and I think the uid mods I keep pointing to in https://github.com/PrairieLearn/PrairieLearn/issues/3170 impact a number of courses that derive the workspace, so they've baked in those edits to their own versions sometimes. But I think these things go beyond/are breaking compared to just bumping the version here.

If you'd like to just bump the existing version, keeping all the existing caveats, I wouldn't mind making a PR for a separate version that has v4 and the other mods. (Cannot promise it will be today.)

**Comment by firasm** [comment]
@echuber2 - just trying to follow the updating of the VS Code workspace image - do you have a link to your example? I'm trying to build one that's based on VSCode server v4.20.

**Comment by echuber2** [comment]
@firasm I think that if you just bump the base image on the example shown in https://github.com/PrairieLearn/PrairieLearn/issues/3170, that will get you most of the way there, except that you can no longer directly install extensions from Microsoft's store due to licensing. Instead code-server will look for it on the Open-VSX store, iirc. https://open-vsx.org/ If they don't have an extension you need, you could possibly download the extension file and bundle it into the build manually, if the licenses on the extension allow it.

I had put my PR on the backburner but I should try to finish that before the spring semester. It has some other QOL improvements and features so I wanted to work on it a bit more first.
