### ISSUE TITLE
Move RFCs out of codebase, into GitHub issues/discussions

### ISSUE THREAD

**Issue by astrosticks** [PrairieLearn/PrairieLearn#4275]
RFCs are usually handled as new documents in pull requests but are kind of clumsy since you can't directly see the document from the PR page, and they don't actually contribute anything to the codebase by themselves. It would be good to move these into GitHub issues or discussion threads, whichever the author prefers, so not to mess with the PR list and keep all relevant info in one place for an RFC.

@mwest1066 would you accept an RFC label for issues and/or discussions?

**Comment by nwalters512** [comment]
One of the main reason they're contributed as "code" at the moment is so that folks can make line-level comments and suggestions via GitHub's interface. It's much harder to collaboratively edit an RFC described in the body of an issue. It's possible that we should switch to something like Google Docs or Notion for authoring them, but I'd be hesitant to try to develop complex RFCs entirely in the body of a GitHub Issue.

Note that version-controlled "RFCs as code" is a common practice among many open-source projects - [React](https://github.com/reactjs/rfcs), [Rust](https://github.com/rust-lang/rfcs), [npm](https://github.com/npm/rfcs), and [Vue](https://github.com/vuejs/rfcs) do the same, to name a few. We could consider moving them outside of the core repo, though previous efforts to do that usually ended up with the extracted bits later being merged back into the monorepo anyways.

**Comment by astrosticks** [comment]
@nwalters512 thanks for the context!
