### ISSUE TITLE
singleVariant:true doesn't allow multiple attempts

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4347]
The behaviour of singleVariant:true, seems off to me.  I read this:

> the question is set to "singleVariant": true in the question configuration file. In this case, students will get unlimited attempts for the same variant.

But after one wrong attempt, I'm looking at the "new variant" button...   See screenshots in #4346 (which is a related cosmetic issue).

This is with homework:
```
{
    "uuid": "********************",
    "type": "Homework",
    "title": "Homework 3",
    "set": "Homework",
    "number": "3",
    "allowAccess": [
      -----  8< ----
    ],
    "zones": [
        {
            "title": "Problems",
            "comment": "meta meta blah blah blah",
            "questions": [
     ----- 8< -----
                {"id": "shapes_in_3d", "points": 1, "singleVariant": true, "gradeRateMinutes": 2}
            ]
        }
    ]
}
```

**update** What I expected here is that my partial answers would stay in place and I could try again, like if I set `"triesPerVariant": 4200000`

**Comment by mwest1066** [comment]
The `"singleVariant": true` option should go in the `info.json` file for the *question*, not in `infoAsssesment.json`. See https://prairielearn.readthedocs.io/en/latest/question/#the-singlevariant-option-for-non-randomized-questions

**Comment by mwest1066** [comment]
Although incidentally we should add `"additionalProperties": false` to most of the objects in https://github.com/PrairieLearn/PrairieLearn/blob/master/schemas/schemas/infoAssessment.json so that they will report an error in situations like this, rather than silently ignoring the option that they don't understand. See #1327

**Comment by cbm755** [comment]
*oh* silly me!  But then how I got the screenshots?!   Something reacted to that option and I definitely didn't have it in the question info.json...

**Comment by cbm755** [comment]
oh wait, maybe those buttons are from the rate limiting, sorry for noise.  Will experiment more!

**Comment by mwest1066** [comment]
> But then how I got the screenshots?! Something reacted to that option and I definitely didn't have it in the question info.json...

Do you mean the "Single attempt" language on the "Save & Grade" button shown in #4346? That's trying to indicate that you only get a single attempt _at this variant_, which is why it also says "Additional attempts available with new variants". The basic problem we might have any combination of:

1. The current variant allows 1, 2, ..., N, or infinite submissions.
2. New variants are or are not allowed.

@jonatanschroeder added this language to the Save&Grade button and the footer to try and indicate which combination of options are available for the current question, so that students will know how many attempts they have. We'd be very happy to improve the language if anyone has better suggestions!

**Comment by cbm755** [comment]
Everything seems to be functioning as expected, sorry for noise.
