### ISSUE TITLE
Simplified math parser

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#4376]
Feedback from a math prof to investigate a math equation/equivalence parser that's more like Webassign and less strict than sympy. Maybe there's a user-friendlier library or converter we could incorporate?

> For the formula entry, I’m asking about when the student submits a math formula. For instance, if we ask for the derivative of  
> `sin(x^2 + 3)`
> then student would need to enter 
> `cos(x^2+3)*2*x`      or 
> `2*x*cos(x^2+3)` 
> or anything else that simpy would recognize as being symbolically the same.
> This entry format is slightly different from what they’ve been using on Webassign, which does not require the * for products. Webassign also has a clickable menu for many symbols and functions. 
> I also ran into an issue trying to enter `cos^2 (x)` into PL — it required `(cos(x))^2` instead, even though it printed the correct answer as `cos^2 (x)`.
> I didn’t want to ask the students to switch to a new entry format for the exams after they spent hours on homeworks on Webassign, so I only used multiple choice and short numerical answer questions, which worked quite well but required a bit of creativity.

**Comment by echuber2** [comment]
I don't know if there is something available, but since the symbolic input elements rely on Sympy itself, we'd need to put in an extra parsing layer that converts to Sympy syntax. It may be possible to do this as a pre-pass of the text at the simplest level (like using regex). For example, convert `[digit][letter]` pairs to `[digit]*[letter]`. Or, convert `[trig function]^[digit] ( ... )` to... etc. This second case is harder because the parenthesized part may not be in parentheses.

#4385 also mentioned a desire for a symbol toolbar.
