### ISSUE TITLE
Replace usage of underscore.js with lodash

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4654]
There are currently two libraries in use by the system that define a `_` variable: lodash and underscore.js. lodash is used extensively more, but a few pages use underscore.js. There are differences in behaviour (e.g., `_.keyBy` in lodash roughly corresponds to `_.object` in underscore.js) which may cause confusion by developers. I suggest we replace all internal uses of underscore.js with lodash for consistency. I don't think we should remove underscore.js, since some elements have been using it and it's plausible that some instructors may have copied those elements for customization (or used underscore.js in general), but we should avoid using it where possible.

**Comment by mwest1066** [comment]
Completely agreed!

**Comment by jonatanschroeder** [comment]
Related: `pl-file-upload` currently uses a `coreScript` called `lodash.min.js`, which seems to me to be exactly the same as the `lodash` node module, but copied to `public/javascripts`. It probably makes sense to use the node module instead, potentially removing (or at least "deprecating") the copy from the core scripts. Similarly, `pl-drawing` and `pl-prairiedraw-figure` use a similar setup for `underscore.js`.

There is also a copy of `underscore.js` in `public/localscripts/calculationQuestion/`, but I can't find any direct reference to it.

**Comment by mwest1066** [comment]
Code in `public/localscripts/calculationQuestion` is legacy support for v2 questions and is being used within course question code. I think we should just leave this unchanged essentially forever, but make sure that no PL core code uses it.

`public/javascripts` is largely but not entirely legacy. This is still used by `coreScripts` in some elements. I think we should try and transition all built-in elements to use `nodeModulesScripts` rather than `coreScripts`, but we should keep the contents of `public/javascripts` in place forever to support legacy course code.

There are a couple of packages in `public/javascripts` that I'm not sure how to eliminate. I'm not sure whether `sylvester` and `sha1` have npm equivalents? And then we have our own old legacy scripts (`PrairieDraw`, etc). It's probably best to just leave these in place and never touch them again?

Perhaps we should add a `README.md` to `public/javascripts` and `public/localscripts/calculationQuestion` to say that they are deprecated but are being retained (but not updated) for legacy support? And no new code should use them! 😄

**Comment by jonatanschroeder** [comment]
> There are a couple of packages in `public/javascripts` that I'm not sure how to eliminate. I'm not sure whether `sylvester` and `sha1` have npm equivalents?

Isn't the saying "if it exists, there is an npm package of it?" (Yes, I know the saying doesn't talk about npm, but who cares...)

> Perhaps we should add a `README.md` to `public/javascripts` and `public/localscripts/calculationQuestion` to say that they are deprecated but are being retained (but not updated) for legacy support? And no new code should use them! 😄

I'm wondering if, for some of these (e.g., `lodash.min.js`, `underscore.js`), we could use symlinks instead, pointing to a node module? This of course would require the `node_modules` to exist in any installation, which I don't know if it is the case always, but just raising as an option.

**Comment by mwest1066** [comment]
> Isn't the saying "if it exists, there is an npm package of it?" (Yes, I know the saying doesn't talk about npm, but who cares...)

I love it --- it's pretty much true in practice 😄

> I'm wondering if, for some of these (e.g., `lodash.min.js`, `underscore.js`), we could use symlinks instead, pointing to a node module? This of course would require the `node_modules` to exist in any installation, which I don't know if it is the case always, but just raising as an option.

I guess I'm slightly worried about backwards compatibility, given that our local copies are ancient. I mainly want to not break any super old course code that's using them. I hope that they these directories are sufficiently obscure that new code isn't using them? Or do you have other thoughts?

**Comment by jonatanschroeder** [comment]
> There are a couple of packages in `public/javascripts` that I'm not sure how to eliminate. I'm not sure whether `sylvester` and `sha1` have npm equivalents?

There are several `sha1` packages, but the `sha1.js` in this directory is only used in PrairieDraw elements, which to the best of my knowledge is deprecated. It is also referenced by `pl-drawing`, but doesn't seem to be used by it.
