### ISSUE TITLE
Allow passing of dynamically generated files to workspaces

### ISSUE THREAD

**Issue by glherman** [PrairieLearn/PrairieLearn#4662]
Example use case: In our class, we generate a random, obtuse piece of code that can't be easily read or interpreted. The goal is that students need to create a series of test cases to determine what the code does. Currently, we generate the code in servey.py, have the students download the code from the question.html page, and then copy-paste it into the workspace.

**Comment by trombonekenny** [comment]
Expanding this issue to also cover static files, copied in from the question or ClientFiles into the workspace. For example, copying in datasets. From Slack chat on 9/2/2021

**Comment by echuber2** [comment]
Would it be appropriate to do this by base64-stuffing the files into `data`? Or maybe not? If there were an additional mount (similar to the "home" mount) where things like this could be auto-generated, then the entrypoint script for the workspace could copy them into place in the user's home directory or something.

**Comment by echuber2** [comment]
Oh, I don't think `data` is available in the workspace, only in the grader...

**Comment by eddelbuettel** [comment]
Yes, having a set of assets (i.e. directory with content, falling back to just a file) would be very useful for us too.

**Comment by echuber2** [comment]
A directory with content (if not dynamic) is already possible by putting a `workspace` subdirectory in your question. That is:

- info.json
- question.html
- etc.
- workspace
  - file1.txt ...

These things are copied into an empty, persisted mount at whatever is specified as "home" for the workspace in `info.json`. For the RStudio workspace, I suggested setting "home" as `/home/rstudio/workspace` (note, not `/home/rstudio`).

If you want _dynamic_ files, I'm not sure there's a way to customize these per-student and also make the grader aware of them before passing them through the workspace's chain of custody (thus, could be tampered with by the student). Dirk suggested he might have a hacky workaround for that already. To elaborate on the chain of custody issue, you could set up the entrypoint for the workspace to handle starter file generation; the problem is that the resulting configuration can't be passed back to the grader except by collecting the student files, and so students could always mess with the problem specification by which they would be graded.

**Comment by eddelbuettel** [comment]
Ah.  We care (at least right now!) mostly about static files to let me test this.  Seems like it does what we need.

**Comment by echuber2** [comment]
We can add to the grocery list some kind of option to follow symlinks if they are found in `workspace/` and if they point to a directory _higher_ than `workspace/`. Currently placing one there gives ENOENT in the container startup. (This would probably need to be a per-option question to avoid breaking changes, although I think that recursively following symlinks that point _higher_ should indeed be safe, as currently the behavior is simply to fail.)

The purpose would be to deduplicate some starter files and allow central management of the deduplicated files.

**Comment by eddelbuettel** [comment]
Yes, dedup would be a nice touch.  Still unsure how to best / easiest hook things up.  A generic script `dataSetup.sh` that is called by `run.sh`?  Maybe too loose.  A JSON option for parts of serverFilesCourse that PL will copy into workspace? Simpler?  Won't be imminent so may spec it out a bit.
