### ISSUE TITLE
Implement new <pl-template> element

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4701]
Instructors often have blocks of "boilerplate" text that they want to include in questions. This can be done at the moment by hand-written templating in `server.py`. To make this easier, we could have an element like:
```
<pl-template file-name="my_template.html" directory="serverFilesCourse">
    <pl-variable name="zip-file" value="starter_files.zip"></pl-variable-name>
    <pl-variable name="upload-file" value="fibonacci.py"></pl-variable-name>
</pl-template>
```
This would load the file `my_template.html` from `serverFilesCourse`, which might look like:
```
<pl-question-panel>
    You should download the {{zip-file}}, unpack it, write your code, and upload the {{upload-file}}.
</pl-question-panel>
```
This file should be templated (using `chevron` in Python, which is `mustache` templates) with the given variables and inserted in place of the original `<pl-template>` element.

A few thoughts:
* We should be able to use templates recursively, so a template can include other templates. I think this will just work automatically.
* The options for the template should be similar to those for [`pl-file-download`](https://prairielearn.readthedocs.io/en/latest/elements/#pl-file-download-element) or other elements that include files.
* Should we also pass all of `data["params"]` into the template? We can always "relay" variables from `params` like this:
```
<pl-template file-name="my_template.html" directory="serverFilesCourse">
    <pl-variable name="zip-file" value="{{params.zip_file}}"></pl-variable-name>
    <pl-variable name="upload-file" value="{{params.upload_file}}"></pl-variable-name>
</pl-template>
```

**Comment by mwest1066** [comment]
Until we implement this, a workaround from @jonatanschroeder is as follows:

* Put a file called `make_template.py` into `serverFilesCourse` containing:
    ```
    import chevron
    
    def render(template_name, **params):
         with open(template_name) as f:
             return chevron.render(f, params)
    ```
* In a question's `server.py` do something like this:
    ```
    import make_template
    
    def generate(data):
        data["params"]["filled_template"] = make_template.render(
            template_name="my_template.html",
            zip_file="starter.tar.gz",
            upload_file="fibonacci.py
        )
    ```
* In a question's `question.html` put:
    ```
    {{{params.filled_template}}}
    ```
* In this example, we would have a file called `my_template.html` in `serverFilesCourse` that contains:
    ```
    <pl-question-panel>
        You should download the {{zip_file}}, unpack it, write your code, and upload the {{upload_file}}.
    </pl-question-panel>
    ```

**Comment by mwest1066** [comment]
Once this is implemented we should delete the FAQ entry from #4720.

**Comment by eliotwrobson** [comment]
We have a local element that's a simpler version of this. I can work on porting that over and adding the additional features mentioned here.

**Comment by mfbutner** [comment]
I know that I'm a bit late to the party here but what is being described sounds like [Mustache's Partial feature](https://github.com/janl/mustache.js/#partials). @mwest1066 and I discussed it around December 2022 and he showed me that mustache.js does support partials. 

I went to go try it out over Winter break but found that to use partials in mustache.js you need to pass `mustache.render` a mapping from partial name to partial text. This is what the completed example from [mustache.js's documentation](https://github.com/janl/mustache.js/#partials) would have looked like.
```js
Mustache.render(template, view, {
  user: "<strong>{{name}}</strong>"
});
```
Of course the partial text could be stored in file and be read from there. 

As of right now, partials aren't supported in Prairie Learn because there is no way to specify the partial mappings. I think just allowing the specification of partials is the better way to go than to create a pl-template element. They let you do everything you want, including recursive partials right out of the box.

In addition to @jonatanschroeder 's suggestion of how to use templates another way that I've found that "works" is by implementing the render method in server.py. Here is an example. All the files are in a question's folder.

question.html
```
{%> greeting %}
```

greeting.mustache
```
Aren't you looking good there {%> name %}
``` 

name.mustache
```
{% params.first_name %} {% params.last_name %}
```

server.py
```python
import chevron
from typing import Any

def render(data: dict[str, Any], mustache_template: str) -> str:
    mustache_template = mustache_template.replace('{%&gt;', '{%>')
    data['params']['first_name'] = 'John'
    data['params]['last_name'] = 'Doe'
    return chevron.render(template=mustache_template, data=data,
                          def_ldel='{%', def_rdel='%}')
```

Some things to note about this example
1. I had to switch from the default mustache delimiters (`{{` and `}}`) to something else (I chose `{%` and `%}`) because by the time the render function runs Prairie Learn has already done the mustache variable substitutions. But because Prairie Learn doesn't have access to the partials the partials were replaced with empty string. So to prevent the partials from being expanded I switched to different delimiter.  
2. The partial syntax uses `>` but because Prairie Learn has already processed question.html it has already escaped `>` as `&gt;`. [chevron](https://github.com/noahmorrison/chevron) doesn't treat `&gt;` as `>` so I had to switch the `&gt;` back to `>` to fit with the mustache syntax.
3. Although I specified `first_name` and `last_name` in the render function they could have been created in either `generate` or `prepare` and stored wherever was appropriate in data. 
    - I also found that you can just add arbitrary key value pairs to data in render if you wanted to specify values to the template that way
    - Values that need to be generated every time the function is rendered must be put in `render`. Values that should be generated only when a new variant of the question is created should be placed in either `generate` or `prepare`. 
4. [chevron](https://github.com/noahmorrison/chevron) supports partials that are on the file system but you have to specify a starting directory where to search from (`./` by default) and a single matching file extensions (`.mustache` by default). This could make it somewhat tricky if you need partials from both the current question, clientFilesCourse, and serverFilesCourse. The workaround to this is to use chevron's partials_dict argument which allows you to specify a mapping between partial name and partial text just like mustache.js. Here is what the example would look like using the partials_dict
    - ``` python
      def render(data: dict[str, Any], mustache_template: str) -> str:
        partials_dict = {} 
        with open(f"name.mustache") as name_partial:
          partials_dict['name'] = name_partial.read()
        with open("greeting.mustache") as greeting_partial:
          partials_dict['greeting'] = greeting_partial.read()
        mustache_template = mustache_template.replace('{%&gt;', '{%>')
        data['params']['first_name'] = 'John'
        data['params']['last_name'] = 'Doe'
        return chevron.render(template=mustache_template, data=data, partials_dict=partials_dict,
                              def_ldel='{%', def_rdel='%}')
      ```
6. A final side note. I thought it was weird that render in server.py accepts its arguments in the opposite order that the render function for elements does. In server.py it is data then template_html but for elements it is template_html then data.

Certainly some jankiness with my version over @jonatanschroeder 's very nice solution. The only upside mine has is that if something needs to be rendered anytime the question's html is updated and not just when a new variant of the question is generated mine can handle that. This jankiness would also be gone if we choose to support partials directly.

**Comment by eliotwrobson** [comment]
@mfbutner I think that addition of the partials feature is somewhat orthogonal to the introduction of the `pl-template` element itself. The main strength of this as an element is that it allows instructors to avoid manually adding render code to generate functions for questions to include shared blocks of boilerplate text. For example, in our course, the addition of `pl-template` (without the partial rendering) would replace the use of three custom elements we have that all do something less general. I feel pretty strongly that this use case alone is worth the element's introduction.

To your main discussion about chevron's support for partial rendering, I think there should be a way to avoid using nonstandard syntax by reading in the raw files as part of the element's code; I believe the render code for an element itself is processed before characters are processed and escaped. This would be a cool feature to play around with and add to this particular element.

For more detailed discussion, I'd love to start getting some comments on the draft PR I have up for this element here: https://github.com/PrairieLearn/PrairieLearn/pull/6747

This would help us get the ball rolling on what I think will be a pretty useful abstraction and cut out a lot of redundant code on the side of course content developers.

**Comment by mfbutner** [comment]
@eliotwrobson Can you elaborate on how partial support and the `pl-template` are orthogonal to each other? I'm having a hard time seeing it as to mee it looks like partials completely cover what `pl-template` does . If we take @mwest1066 original example and partials were supported then 

`question.html` would look something like
```
{{#params.assignment_details}}
  {{> my_template }}
{{/params.assignment_details}}
```

and `server.py` might look something like this 
```
def generate(data):
    data['params']['assignment_details'] = {
        'zip_file': ' starter_files.zip',
        'upload_file': 'fibonacci.py'
    }
```

`my_template.html` would remain unchanged and still be
```
<pl-question-panel>
    You should download the {{zip_file}}, unpack it, write your code, and upload the {{upload_file}}.
</pl-question-panel>
```

So we were able to use Mustache's partials as a way to have some boilerplate text that we could reuse across multiple questions. The only reason that it doesn't work right now is that there isn't a way to specify what partials should be used when rendering. The other current limitation is that if there is something that needs to be updated on each render and not just on question generation there isn't really a way to do this. The only time I've needed that to happen though was when I was doing something like @jonatanschroeder 's suggestion for putting in my prompts to a question and had a typo in them that I didn't notice until after the assignment was released to students. 

One advantage of `<pl-template>` over partials is you have the option to specify the values to substitute in, inline if you so choose.

The jankiness in what I showed earlier is how you could use partials now, given that they are directly supported and even to me looks like a less than ideal solution.

I'll take a look over your post as soon as I have a chance.

**Comment by eliotwrobson** [comment]
> Can you elaborate on how partial support and the `pl-template` are orthogonal to each other? I'm having a hard time seeing it as to mee it looks like partials completely cover what `pl-template` does .

I guess in my mind, I view the primary benefit of this element as a way to reduce code bloat rather than as just another way to render boilerplate. The issue is that, even in the example you give, the instructor still has to write code that lives in `server.py`. In many cases, there are questions where this code would be the only code there, and this necessitates the creation of an extra file for every question that uses the desired boilerplate.

Although this isn't a big deal for a single question, for a large course, this can result in the creation of many more python files that make the course code harder to maintain and make python tooling run slower.

> I'll take a look over your post as soon as I have a chance.

Thank you!
