### ISSUE TITLE
Empty file upload for pl-file-upload element produce strange file content on auto-grader

### ISSUE THREAD

**Issue by steven-wolfman** [PrairieLearn/PrairieLearn#4828]
Uploading an empty (0 byte) file to a pl-file-upload element and grading via an external grader creates a file that is non-empty and contains non-standard characters which are not viewable in the file preview.

This can be reproduced using one of the XC 101 problems, such as demo/autograder/codeUpload: https://ca.prairielearn.com/pl/course/1/question/4/preview

Sorry for the awkward bug report. I'm out of time for this today!

**Comment by jonatanschroeder** [comment]
I just tested and can confirm this is indeed happening. The problem seems to be that during the upload of the file, base64 is used to represent the data, but at some point a blank file is represented in what should have been base64 as `data:` instead of a blank file. It seems that then this `data:` is interpreted as the base64 info (which would explain the weird characters) and used to transfer the file to the external grader.
