### ISSUE TITLE
Timed exam assessment

### ISSUE THREAD

**Issue by zillesc** [PrairieLearn/PrairieLearn#484]
Add support for timed assessments, where a time limit can be specified, and the student can choose when to begin the assessment, but it must be completed within the specified time after beginning.

**Comment by kevinwang** [comment]
I wonder how this would affect code upload questions, since many students submit their code after time is called. My concern is that instructors would get a lot more emails like, "I couldn't submit my code in time. Can you get it from my home directory?"

In a CBTF setting, we could probably incorporate a grace period into the timer (like 55 minutes instead of 50 minutes) for students to upload their code. Alternatively, we could not use the timer at all for CBTF exams and leave it to the proctors' discretion. For home assessments, we can probably just make it the student's responsibility to submit on time.

**Comment by mwest1066** [comment]
I think at this point Craig wants this for out-of-CBTF "tests" that are very brief. I'm still not exactly sure how to handle in-CBTF timed testing.

**Comment by trombonekenny** [comment]
+1 for @kevinwang looking out for anything that might cause instructors to make admins go fishing in home directories.

**Comment by kevinwang** [comment]
:+1: for this feature request -- it turns out that CS 225 has a medium/high-priority use case for this!

**Comment by mwest1066** [comment]
Can you explain the details of how 225 would want to use it?

**Comment by kevinwang** [comment]
We wish to administer PL quizzes in our lab sections. However, we also want to enforce that the quizzes are only taken in lab section.

There are two issues preventing us from using exam mode for quizzes: (1) students would be able to see exams as well (since there are only two modes, Public and Exam), and (2) students use their own laptops in laptop lab sections.

Our proposed solution is this.

1. Students swipe into lab for attendance using existing 225 course software. This software will be augmented to also provide the student with a random password.
2. Upon receiving the password, students will have *m* minutes to start their assessment. The first question of the assessment will ask for the password provided to them by the attendance app. Students will then have *n* minutes to complete their quiz.
3. We will grade the quizzes offline and verify the password and that the start time is within *m* minutes of, but not before, the swipe time.

The timed assessment feature, in particular, will prevent students from answering/collaborating on the quiz questions in advance and then just adding the password and submitting when they go to their lab section.
