### ISSUE TITLE
Add vertical lines to pl-order-blocks to show indentation points

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4921]
(e.g., https://github.com/ace-lab/berk-parsons/blob/79cd59dca70e0ac8156c9386bc8c0b1fcbd94fc0/app/static/vendors/parsons/parsons.js#L1470-L1477, https://github.com/RunestoneInteractive/RunestoneComponents/blob/05d5a5d0a03369fb7726474d68f07b7dbd2d7c26/runestone/parsons/css/parsons.css#L100-L109)

originall suggested by @nathanielweinman over at https://github.com/PrairieLearn/PrairieLearn/issues/3476

**Comment by ataraxie** [comment]
@SethPoulsen I had a look at this one first, trying to dig my way into pl-order-blocks a little. Let's first see if I understood the requirement. I like to use screencasts to explain these things, so below are a few videos linked...

For a pl-order-blocks element with indent enabled, it's currently hard to see for what indent level an element gets dropped: see [this video](https://recordit.co/CQRAyA4xV3) (taken from the `orderBlocksRandomParams` example question).

Runestone Academy makes this more obvious with vertical lines that indicate the available levels of indentation: see [this video](https://recordit.co/ub1bGuKQsl) (taken from the Runestone docs [here](https://runestone.academy/runestone/static/authorguide/directives/parsons.html)).

If I simply adapted this, it would look like in [this video](https://recordit.co/oYW6fLxnRX) (same example as above with vertical lines).

Firstly, let me ask: am I understanding this right? Assuming so, here's a few problems that I'm seeing:

1. The container for the elements ("dropzone") has a padding of 17px. This makes it confusing where the elements should actually align. This is not the case in the Runestone example where there's no padding and the elements end up directly at the line. Introducing another container around the dropzone and giving that the padding might be a solution.
2. In the Runestone example, the vertical lines have a height of 100%. This also does not work in our case with the padding. This could also be solved with a container around the dropzone as described before. Otherwise the only way would be to change the height dynamically with JS - not a good idea.
3. While dragging an item into the dropzone initially, the item is not "jumping" according to the indents in the dropzone, but the movement is fluent. This might be an independent UX issue (this is not present in the Runestone example).
4. I find the highlighted layer behind the item (showing where the item would be dropped) very confusing when there's indentation: it always spans the whole width even though I'm dropping the item at an indented position. This might be another independent UX issue.

This should be a good communication starter 🙂

**Comment by SethPoulsen** [comment]
1. I do like having a little padding on the dropzone, but it doesn't have to be as much as it is. Maybe we could add a vertical line at the 0 indent location? (so the line would be pretty close to the actual border of the dropzone?) Obviously either way, we want the lines to actually match up with where the blocks are dropped.
2. Can't we just do something like `calc(100% - Xpx)` where `X` is the amount of padding?
3. I think it would be cool to have it snap to the indent locations like the Runestone one does. I think it would make it easier to use (but anyone else is free to disagree with me)
4. I think everyone would agree that the current highlighted layer is a problem. I think I was going to make another issue about  but forgot. It should definitely show where the block is actually going to drop, not the whole width. Feel free to fix in the same PR as this. 

These issues might also go well in a PR together with this one (don't have to though): 
https://github.com/PrairieLearn/PrairieLearn/issues/4922
https://github.com/PrairieLearn/PrairieLearn/issues/4926
