### ISSUE TITLE
pl-order-blocks: easier code formatting

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4924]
It is possible to get code formatting by wrapping the text in each of the blocks with `<code></code`, but this is a little clumsy. 

Maybe we should put a new option on pl-order-blocks so that it will just wrap each of the blocks with `<code></code>` for you?

**Comment by lslavice** [comment]
Aha! Your comments made me think I was missing something obvious, and I was. My local copy of PL I think must be out of date because when I was testing things locally, none of the answers that were in code font would appear. But I just pushed it to the actual course on PL, and I get at least what you are talking about: lines are in code font, but with extra margins. And I can have a block with multiple lines in it, which also wasn't rendering locally. See below (this is just using `<code>` not `<pl-code>`:

![image](https://user-images.githubusercontent.com/70032904/137359267-4b11e92d-0ccd-46ae-9243-fa78dc4c3929.png)

(And that's what I meant by "multiple lines", although I'm totally down for the dragging multiples of the same thing over like in issue #4055  so I don't have all these random curly braces and weird ranking logic or whatever.)

I am still new to PL, so thank you for your help and sorry if I caused confusion! Mostly, I just wanted to throw support at the `pl-order-blocks` having a nice way to make them all be `pl-code` styling, because that would be very nice. :)

**Comment by SethPoulsen** [comment]
Ya, that double margin thing really isn't very pretty. 

I think we should probably have a way to have the code styling apply directly on the blocks instead of having the extra box inside of them, especially since this element is so commonly used for code.

**Comment by SethPoulsen** [comment]
Currently no one is working on this anyone can feel free to have a go.

**Comment by echuber2** [comment]
Trying to clarify: Is it desired that nested blocks *should* auto-indent on the solution assembly column? Or that they _should not_?

**Comment by SethPoulsen** [comment]
The element has no way at all of being aware of the content of the blocks, and we have no way of doing auto-indentation or any plans for adding that.

This issue is about making the formatting of code inside of pl-order-blocks more pleasant, by making it look better and by making it easier to write the HTML.

My comments above are with regards too making it so that there is only a single margin in the blocks. 

Currently, is you do `pl-code` inside of `pl-order-blocks`, there is a margin between the edge of the block and the code formatting, then there is _another_ margin between the edge of the code formatting and the actual code. 

We need the code formatting to applied directly to the order block, instead of having another div inside it. this will look much better.

**Comment by echuber2** [comment]
OK. I was confused about the example in https://github.com/PrairieLearn/PrairieLearn/issues/4924#issuecomment-943530341 . Perhaps it would do to have mockups here of what it looks like currently and what it _should_ look like.

**Comment by SethPoulsen** [comment]
This is what it _should_ look like. 
![image](https://user-images.githubusercontent.com/25016959/166612434-4b1edfce-2469-4ac0-9e75-c5bc3f8e751d.png)

It was actually pretty straightforward to hack the CSS to get this going. I can probably put up a PR tomorrow.
