### ISSUE TITLE
pl-order-blocks UI sometimes allows negative indentation

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4926]
Seems to be an intermittent problem. Need to test more to see when exactly it occurs.

**Comment by ataraxie** [comment]
@SethPoulsen @nwalters512 I closed the associated PR #4963 because I performed refactorings that weren't associated with the actual issue and in the end the bug didn't seem to be fixed after all.

I wanted to create a new minimal-change PR, but I realized that it's not so easy without a full understanding of the original code. Of course it would be easy to just set the margin to 0 if the variable `leftDiff` is negative (see screenshot below), but I think this would be more of a hack than a solution. I think either this should be fixed by the original author of the file or the file should first be reworked as I proposed in PR #4963.

Overall, I must say that I don't feel very comfortable contributing this way because I feel like with any change of this kind I'm just contributing to making this code less intuitive and it might just lead to new bugs.

![image](https://user-images.githubusercontent.com/1646086/137109876-be5985c1-b080-4940-bd31-edda3cdc2e80.png)

P.S. side note, just because I noticed it (feel free to ignore): another problem I consider really major is that this script (probably unintentionally) introduces a global variable `MAX_WIDTH` on `window`. This can be quite dangerous. A first solution would be to use `const` or `let`, but a proper solution would be on an architectural level: it should be ensured that any scripts created for elements are wrapped in a closure. I've used Webpack to achieve this in the past (which would also enable a whole lot of other options).

**Comment by nwalters512** [comment]
@ataraxie I understand, thanks for posting an update here. If you _can_ fix the bug with a larger refactoring, I'd happily accept that as long as the refactoring doesn't change things unrelated to the bug (for instance, introducing additional jquery code).

> another problem I consider really major is that this script (probably unintentionally) introduces a global variable MAX_WIDTH on window.

Good catch! The element as a whole doesn't seem to follow our best practices, unfortunately 😢 

> I've used Webpack to achieve this in the past (which would also enable a whole lot of other options; one I would consider useful for PL is CSS-preprocessing, for example).

This is another thing that's somewhere on my todo list, though not a super-high priority. I'd love to improve the tooling for frontend JavaScript so we can, for instance, avoid polluting the global scope and use modern language features + TypeScript.

**Comment by SethPoulsen** [comment]
> Of course it would be easy to just set the margin to 0 if the variable `leftDiff` is negative (see screenshot below), but I think this would be more of a hack than a solution.

I'm having a hard time seeing why this is a problem. Its coming from a user input, so we really can't control what it is by restricting its type or anything. Personally I'd be fine with a 2 line commit that does this.

I totally agree with you guys that there are many more improvements we could make to the codebase, but I don't see why we should let that prevent us from merging a 2 line fix to this bug.

**Comment by SethPoulsen** [comment]
I mean, if it makes you more comfortable, we could put the check closer to where the user input is first processed, meaning here: 

https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-order-blocks/pl-order-blocks.js#L114-L116

**Comment by SethPoulsen** [comment]
I've made a new issue about cleaning up the file and added it to the order-blocks project board: https://github.com/PrairieLearn/PrairieLearn/issues/4980

**Comment by SethPoulsen** [comment]
I apologize; after digging into it more myself, I realized that the indent calculation was more complicated that I thought. However, I couldn't actually see any reason for it to be complicated. 

I did this: https://github.com/PrairieLearn/PrairieLearn/pull/4981

and as far as I can tell, the behavior is exactly the same (except for not allowing negative indent). Thoughts?

**Comment by SethPoulsen** [comment]
If people aren't comfortable with that big of a change honestly I'd still just prefer slapping an if statement around this line: 
https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-order-blocks/pl-order-blocks.js#L91 
over having the bug.

**Comment by ataraxie** [comment]
I don't have strong opinions here, your fix seems ok. I just find it much better that the change comes from you who is the lead behind this element 🙂
