### ISSUE TITLE
pl-order-blocks: confusing shadow when dropping blocks for indentation

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4936]
![image](https://user-images.githubusercontent.com/25016959/136617369-f6f6d752-2ece-4c5a-b296-b399a5f5ce4a.png)

When dropped, this block will be indented, but the shadow behind it makes it look like it won't be.

**Comment by SethPoulsen** [comment]
@Frozemint do you know which line of code we need to tweak to fix this?

**Comment by Frozemint** [comment]
Good question. The "shadow" is part of the jquery sortable placeholder: https://jqueryui.com/sortable/#placeholder 

The reason why the shadow is not indented is because we are definitely pushing the jquery sortable way pass its intended use cases. It might be possible to indent the shadow by styling the `placeholder` class and adding margin-left, the same way we indent the other blocks.

This should largely be fixed by changing CSS code, at least I think so (read: at least I hope so).

**Comment by SethPoulsen** [comment]
It seems we should be able to hack on the CSS and make it work.

**Comment by Frozemint** [comment]
Yep, I checked the code again and the class you want to style is the `ui-state-highlight` class. You can change this by changing this line in the code: https://github.com/PrairieLearn/PrairieLearn/blob/1760ad025157d37199af506c34e2e1ec7327d921/elements/pl-order-blocks/pl-order-blocks.js#L102

**Comment by ataraxie** [comment]
Not sure if this is so easy to implement. The only way I'm seeing at the moment is to change the width/position of the placeholder dynamically while an element is dragged. And while that's done, the mechanism finding the correct indent needs to apply as well. This could also become costly when performed while dragging.

Is this placeholder a much desired feature of order blocks or is it mostly a side-effect of the library?

**Comment by Frozemint** [comment]
The placeholder is a feature from the library, and I used it because I thought it was clearer to the user where the block would land. At the time I didn't worry about indents yet. 

I think the placeholder feature is intended as a simple shadow, that's why adding indents might be difficult (because this is not part of the intended use cases 😅 )
