### ISSUE TITLE
Use Black to format Python code

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#5027]
Just like we now use Prettier for JavaScript, we should use [Black](https://github.com/psf/black) to automatically format our Python code.

**Comment by eliotwrobson** [comment]
Since there seems to be discussion of reworking the CI job in #6447, this could be incorporated there. The only issue is that Black is incompatible with the way the current formatting is set up, we would have to remove stuff like `flake8-quotes`. It might also be worth setting up isort as well: https://pycqa.github.io/isort/
