### ISSUE TITLE
Custom element feedback issue

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#5523]
In writing a custom element, we're seeing an issue where, after modifying `data['feedback']` in the `grade` function, that dictionary entry is cleared out when the `render` function is called next. Specifically, our code looks something like this
```
def render(element_html, data):
    print(data['feedback']) # prints the empty dictionary, other operations behave as if this is empty

def grade(element_html, data):
    ...
    data['feedback'][question_name] = 'feedback for question'
```
The specific pull request where we're having this issue can be found [here](https://github.com/PrairieLearn/pl-uiuc-cs374/pull/195).

**Comment by nwalters512** [comment]
I'm pretty sure this is just a documentation bug; sorry about that! We explicitly zero out the `feedback` object after processing question HTML (read: calling element functions):

https://github.com/PrairieLearn/PrairieLearn/blob/21c26abd8efedc4e0c1d4558c01b901280c7b0c8/question-servers/freeform.js#L866

I'm not 100% sure why we do that, but I suspect it's because elements aren't supposed to contribute to that object; only the question itself (in the form of `server.py` or via external/manual grading) should set that.

Unfortunately, this doesn't match [the documentation](https://prairielearn.readthedocs.io/en/latest/devElements/), where we explicitly list `feedback` as being modifiable by element `grade()` functions:

<img width="616" alt="Screen Shot 2022-03-17 at 11 35 31" src="https://user-images.githubusercontent.com/1476544/158872552-e3b6c034-503b-477b-8af4-addbf00de7e0.png">

I believe what you actually want is to set `data['partial_scores'][name]['feedback']`; this is what all first-party PL elements do. For example:

https://github.com/PrairieLearn/PrairieLearn/blob/21c26abd8efedc4e0c1d4558c01b901280c7b0c8/elements/pl-multiple-choice/pl-multiple-choice.py#L353

I'll need a second set of eyes from @mwest1066 to figure out if we need to change the behavior or the docs (the `feedback` object in the database is ancient!), but I suspect it's the latter. I hope this is enough to unblock your course in the meantime though. Please let me know if you have any questions!

**Comment by eliotwrobson** [comment]
Ahhh I understand, the feedback entry in the data dictionary is meant for generalized feedback (not necessarily specific to any one part of the question), but the feedback entry in the partial scores is intended for the specific element to handle.
