### ISSUE TITLE
Exam "duration" displays an incorrect duration

### ISSUE THREAD

**Issue by wadefagen** [PrairieLearn/PrairieLearn#567]
The duration (as reported on both the bar chart and [1]) does not accurately reflect the time a student spends on the exam.

In the specific case linked in [1], the timestamps are:
- [Begin]: 2017-01-29 15:00:11 (CST)
- [Submission of Q1]: 2017-01-29 15:12:21 (CST)
- [Submission of Q2]: 2017-01-29 15:18:09 (CST)
- [Close Exam]: 2017-01-29 15:19:12 (CST)

The expected duration would be: 19min 1sec (19 min).

The duration reported in PL is: 5 min.

[1]: https://prairielearn.engr.illinois.edu/pl/course_instance/470/instructor/assessment_instance/12067

**Comment by mwest1066** [comment]
This is because we currently only count submissions as events when computing durations. We should also include the begin assessment event. See https://github.com/PrairieLearn/PrairieLearn/blob/master/sprocs/assessment_instance_durations.sql

For an example of including the dates of `assessment_instance` creation (the "start exam" events), see https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorAssessmentInstance/instructorAssessmentInstance.sql#L13

**Comment by mwest1066** [comment]
See also #458
