### ISSUE TITLE
LTI grades only being sent by individual regrade (Coursera)

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#5671]
The CS 445 staff flagged this issue and I've confirmed that with LTI items linked from Coursera, the grades are currently only being sent back if we select Regrade for student instance records *one at a time*. Attempting to close+grade or expire/reopen/re-close+grade all of the assignments doesn't work. This is different from the behavior in past semesters where LTI grades went back as soon as the student finished the exam item.

Is this a bug or an intentional change in behavior? If we don't attempt to manually regrade items, will they all be transmitted in bulk automatically after some period of time? Would it be possible to add the transmission trait to the "grade all instances" action?

Tagging @trombonekenny for his expertise on LTI.

**Comment by trombonekenny** [comment]
I think this might be a regression, not on purpose. LTI outcomes should get updated each time a score is updated. Maybe something changed in `lib/question.js` - do we know when this stopped working?

**Comment by trombonekenny** [comment]
The LTI code is coming from `ltiOutcomes.updateScore`

**Comment by mwest1066** [comment]
There was a recent refactoring of this code when @nwalters512 changed the locking structures. It's possible that something broke then.

**Comment by trombonekenny** [comment]
Down the road, I think we'd want to change this kind of function to be pub/sub where grading wouldn't need to do the LTI phone home but queue it somewhere. I don't know if that pattern exists in PL development or could be extended for updateScore()

**Comment by nwalters512** [comment]
@mwest1066 and I independently stumbled across this bug while working on unrelated code. The breadcrumbs start here:
 https://github.com/PrairieLearn/PrairieLearn/blob/529f6dffb1b5b79d1d0ebf777a99741eab8f6aa7/lib/question.js#L634

My update in #5489 changed the preceding code to call `grading_jobs_update_after_grading` instead of `grading_jobs_insert`. `grading_jobs_insert` actually returns a grading job, whereas `grading_jobs_update_after_grading` does not. That means we unconditionally skip over the LTI reporting in the next function.

I don't have time to fix this immediately, but this should be a pretty easy PR for someone who wants to take this on.

**Comment by trombonekenny** [comment]
Ooooh I love one liners.
