### ISSUE TITLE
ECE 110 graph generator tool not working on v2

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#577]
Chris Schmitz is using a student-written library for graphing that's not working right with v2.

https://github.com/PrairieLearn/pl-ece110/blob/master/serverFilesCourse/ECE110Graphics.js

We talked about it at office hours; he's not necessarily in love with the generation code. But he's looking for an understandable, supportable way to insert a dynamic graphic into his questions around MOSFETs.

He has a few weeks until those questions get released to the students. He'd like to get something figured out sooner than that so he can continue the question development. I told him we'd follow up with him after Matt gets back.

**Comment by trombonekenny** [comment]
Needs d3?

**Comment by mwest1066** [comment]
This error is because PLv1 used to include `d3`, but we don't include it anymore in PLv2. I added it to `pl-ece110/clientFilesCourse` and updated `questions/TempGraph/client.js` to include it. For other questions that use your `ECE110Graphics` library you will need to use this modified `client.js` that uses `d3`.
