### ISSUE TITLE
Error messages reveal backend details

### ISSUE THREAD

**Issue by ijustlovemath** [PrairieLearn/PrairieLearn#586]
When the page expires and is reloaded, sometimes you get a message like:

Error processing request
Incorrect rowCount: 0
Error ID: <id>

This is a pretty common error from MySQL databases, and giving explicit details like this could lead to potential future exploits. A quick search through the repo shows this line as generating this message:

https://github.com/PrairieLearn/PrairieLearn/blob/72e8e4de15e75129e40bbb2420df647359ee296e/pages/error/error.ejs#L17

**Comment by mwest1066** [comment]
Are you referring to the `Incorrect rowCount: 0` line or the `Error ID` line when you say "explicit details like this"?

**Comment by ijustlovemath** [comment]
Yes. In this instance the information is relatively harmless, but directly
showing error information from the database in your web application can be
used to probe for exploits.

**Comment by mwest1066** [comment]
Closing in favor of #592. This is not a security issue because the current errors shown are not actually DB errors. The `Incorrect rowCount` is an app server error meaning that a query failed to return the expected result, but does not indicate anything further. The `Error ID` is constructed explicitly to show to the user, so that user-visible errors can be cross-referenced to server error logs, and it does not reveal any information (it's a randomly generated string).
