### ISSUE TITLE
sqldb parameterized "LIMIT ALL"

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#619]
Putting "LIMIT ALL" in a psql query should do the same thing as omitting the limit statement, but when "LIMIT $limit" is parameterized, something doesn't like the string ALL not being an integer. Can we fix that?

**Comment by mwest1066** [comment]
Not easily. But for a good reason. Putting `ALL` in there is not doing a parameterized query, but is rather trying to construct the SQL on the fly by string manipulation. This is disallowed because that's how you get SQL injection vulnerabilities.

In the case of LIMIT, apparently `LIMIT NULL` is also the same as `LIMIT ALL` so I think should be able to just pass a JavaScript `null` for the `count` parameter and it should all work.

**Comment by mwest1066** [comment]
Closing as resolved by the `null` trick. Please re-open if that doesn't work.
