### ISSUE TITLE
Cannot copy group assignments from one assessment to another

### ISSUE THREAD

**Issue by DallasTrinkle** [PrairieLearn/PrairieLearn#6256]
In the groups tab for assessments, there is the option to copy group assignments from a previous assessment. After selecting the assessment with the group assignment, it fails and returns with the error: 
```
Error processing request: 
duplicate key value violates unique constraint “group_configs_assessment_id_key”
```
There isn't an existing group assignment for this assessment. However, group assignments can still be uploaded from a CSV file successfully, so I suspect the underlying assessment is fine and this is a PL issue.

**Comment by nwalters512** [comment]
AFAICT, this is because the [`assessment_group_copy` sproc](https://github.com/PrairieLearn/PrairieLearn/blob/bb8cae5491a96d05136be245b7925b67a8464632/sprocs/assessment_groups_copy.sql) is just straight-up broken. It tries to soft-delete old group configs before inserting a new one, but we have a unique constraint on `assessment_id` for the `group_configs` table.

I think this was actually working correctly when groups were first implemented, as the original unique constraint included `WHERE deleted_at IS NULL`:

https://github.com/PrairieLearn/PrairieLearn/blob/bb8cae5491a96d05136be245b7925b67a8464632/migrations/20200817231422_group_change_assessment_inst.sql#L19-L20

However, https://github.com/PrairieLearn/PrairieLearn/pull/3859 changed that to not filter on `deleted_at`, but didn't update the sproc to not perform soft-deletes.

**Comment by nwalters512** [comment]
Related to this, I think it's a mistake to copy `group_configs` when copying group, as `infoAssessment.json` should always be the source of truth for that. We should remove the code that does this. We should ensure that the group assignments being copied are compatible with the group settings of the assignment they're being copied to. For instance, if we're copying from assessment A to B, we should ensure that none of A's groups are smaller or larger than the max or min sizes that are configured for B.

**Comment by bowmnath** [comment]
I think Nathan is right that this worked originally, but it has been broken for a while now (see #3866).  If it is a difficult fix, it might be good to remove the option from the dropdown for now to avoid confusion.

**Comment by firasm** [comment]
Can confirm this is still broken 😅

<img width="1366" alt="Screenshot 2023-02-13 at 9 55 51 PM" src="https://user-images.githubusercontent.com/2507459/218652403-ce80ebed-b643-4d88-89a7-1e33cd9da15b.png">

workaround of downloading the csv from one assignment and then re-uploading into another one seems to work fine.

**Comment by nwalters512** [comment]
Closing in favor of #8911. We've removed the (broken) copying functionality for now; we'll see about reimplementing this in the future.
