### ISSUE TITLE
missing clientFilesCourseInstance folder throws unhelpful error message

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#6308]
We discovered this with an assessmentInfo.json `text` pointing to `<%= clientFilesCourseInstance =>/formulas.pdf` when the course instance `clientFilesCourseInstance` folder doesn't exist. PL errors:

The "path" argument must be of type string. Received null.

![image](https://user-images.githubusercontent.com/10765199/189539314-0df83728-9db9-45ee-a1f7-115441e425af.png)

We should make that error more descriptive about missing folders or paths.

**Comment by mwest1066** [comment]
The error is in the chunk code. If we try and access a file in `clientFilesCourseInstance` when there is no `clientFilesCourseInstance` directory then the chunk code misbehaves. Rather than a "file not found" or similar error (with a 404 or other 4xx status), we get a `status: 500` error as shown below.

## Stack trace

```
The "path" argument must be of type string. Received null

Async Stacktrace:
    at Object.<anonymous> (/PrairieLearn/pages/clientFilesCourseInstance/clientFilesCourseInstance.js:25:9)

TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.join (node:path:1172:7)
    at Object.module.exports.coursePathForChunk (/PrairieLearn/lib/chunks.js:212:19)
    at /PrairieLearn/lib/chunks.js:984:38
    at Array.map (<anonymous>)
    at Object.module.exports.ensureChunksForCourseAsync (/PrairieLearn/lib/chunks.js:980:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## My guess about what is wrong

My guess is that `chunkMetadata.courseInstanceName` is `null` here:
https://github.com/PrairieLearn/PrairieLearn/blob/8e752630568f07b018096aaa7f93d92f0dd1335c/lib/chunks.js#L215

We got there by trying to get a `type: 'clientFilesCourseInstance'` chunk: https://github.com/PrairieLearn/PrairieLearn/blob/8e752630568f07b018096aaa7f93d92f0dd1335c/pages/clientFilesCourseInstance/clientFilesCourseInstance.js#L21

So I'm thinking there is something wrong in `ensureChunksForCourseAsync()` when handling chunks that don't exist?

@nwalters512 can you spot how this could happen?

**Comment by nwalters512** [comment]
#6311 should fix this 🤞
