### ISSUE TITLE
Early stopping in Python Autograder grading scheme yielding point total issues.

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#6385]
Consider an auto-graded question with three tests:

- 1 point first test
- 2 points second test, and;
- 9 points for the third test

Total: 12 points

If we stop the grading suite early, say when only 2 of 3 tests are completed, the outcome reported to students is 1/3 points. However, the percentage is shown as 8.3% as we have 1/12 points earned from the total: 

<img width="307" alt="sample-test-complete-with-early-stopping" src="https://user-images.githubusercontent.com/833642/193341115-815e9bf7-a0d2-48cf-81d4-1340f0f1ea1d.png">

Effectively the student sees 1/3. Thus, we would assume 33.3% of the grade would be given. However, the “full” portion seems to be what PrairieLearn is using to calculate their grade.

<img width="223" alt="python-autograder-points-returned-early-stopping-test" src="https://user-images.githubusercontent.com/833642/193341077-b8fd16b7-e8b2-444a-ba4e-f5b79fda1679.png">

**Comment by nicknytko** [comment]
So, it looks like this discrepancy happens because the percentage value is returned out of the *true* maximum points,
https://github.com/PrairieLearn/PrairieLearn/blob/63921c2c4b6f5e2b2ba6cf7fa8f17a48acea8d30/graders/python/python_autograder/pl_main.py#L107
while the maximum point value that is shown to the student is computed in the results element:
https://github.com/PrairieLearn/PrairieLearn/blob/63921c2c4b6f5e2b2ba6cf7fa8f17a48acea8d30/elements/pl-external-grader-results/pl-external-grader-results.py#L97
since grading is stopped early the later test cases aren't sent back to PL and thus we display the wrong point value.

I think the simplest fix (without having to change a bunch of json schema) would be to always show every test case, no matter if we end grading early or not.  Thoughts on this?

**Comment by coatless** [comment]
@nicknytko I have no problem exposing the later tests. For my use case, I'm verifying a specific completion condition. e.g. "no loops" or "no importing {module}", after testing for accuracy.
