### ISSUE TITLE
Review autograder notify the course staff messaging

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#6491]
In the testing center, we often encounter students seeking help with their question tells them to contact the course staff, i.e. 

```
The grading code was not able to run.
Please notify the course staff and include this entire message,
including the traceback below.
```

When the error is most typically due to bad student input, and the error is solvable by the student. I think the cautiousness around "notify the course staff" was when the autograder was new and maybe the course hadn't thought about all the edge cases that students might throw at it. But in practice, I can't see the system giving advice to "ask your TA" every time they code something badly.

Could we change that language in our graders to something more descriptive and immediately helpful? Like:

```
Something unexpected happened. Please read and consider the error message below 
that happened when the autograder tried to run your code.
```

Or if there is helpful feedback that channels back to the course staff from these kinds of messages, perhaps we can toggle the language to do different things when `"mode": "Exam"` that's more appropriate for how to get help in different contexts?

**Comment by jonatanschroeder** [comment]
Just noting that this is specific to the Python autograder. Other autograders do not typically give out this message.

**Comment by trombonekenny** [comment]
Bump because this is (continually) a problem in the CBTF. It confuses students, it frustrates the proctors and me who have to keep answering with what the message really means (your code bad is bad, review it, try again, do your best, read the error, etc.).

**Comment by trombonekenny** [comment]
Another student/proctor question about this.

**Comment by nwalters512** [comment]
@nicknytko AFAICT, this is a false positive for detecting broken grading code that's outside the student's control. This conditional appears to be failing:

https://github.com/PrairieLearn/PrairieLearn/blob/ce0d20ba002b2e970554e5979e4223607b9a5201/graders/python/python_autograder/pl_result.py#L105

Locally, I added some extra logs, and I can see that `test_id` in the above case is actually `filenames.test.Test.test_1`. If I remove that branch of the conditional, I get useful feedback as a student:

<img width="845" alt="Screenshot 2023-02-26 at 14 16 12" src="https://user-images.githubusercontent.com/1476544/221440752-84fe9b5a-6dae-4c31-a167-a6743b4b436b.png">

I like the principle of showing a different error message if we can tell that an error is outside the student's control, but we need to be *really* sure of that before we show the "contact the course staff" message. I can't tell what the code is supposed to be checking for at the moment. Do you know what the right way to fix this is? Otherwise I'm inclined to remove the "ungradable" branch here.
