### ISSUE TITLE
API/CSV access to student IP addresses

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#6532]
Instructors may want to see the IP address students used to access PL during an assessment (for academic integrity investigations, for example). It would be great to make this info available via API and/or in the CSV downloads.

**Comment by ffund** [comment]
(also via the assessment log!)

**Comment by mylesw27** [comment]
This issue was addressed and resolved by #8798 and #9082. Client fingerprints now allow us to store information about the devices used to access assessments including the user agent and IP address. Because of this, we are now able to access the IP address in the assessment instance log endpoint of the API when the client fingerprint is stored in an event. We have also added a column to the CSV file that displays the IP address for any events with a client fingerprint.
