### ISSUE TITLE
Sync warnings are not listed during sync process

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6546]
Some sync warnings are not shown during the sync process, even though they trigger a sync warning shown on the exam setting.

![image](https://user-images.githubusercontent.com/1004907/199117790-7a6bc511-35fb-4c7d-960c-bf08f9cfd3fe.png)
https://ca.prairielearn.com/pl/course_instance/2450/instructor/jobSequence/67500

In the example above the sync warning was for an access rule with an exam UUID that didn't exist on PrairieTest. Finding the offending exam was not trivial as it was in an assessment for a previous term, and this warning is not shown in the local environment.

**Comment by nwalters512** [comment]
This occurs because we only logs details for errors and warnings before we start writing to the DB:

https://github.com/PrairieLearn/PrairieLearn/blob/440bad12fa5afdc84d4c4a3fc652645b1cbcb62d/sync/syncFromDisk.js#L49

However, some warnings are actually discovered and stored after that:

https://github.com/PrairieLearn/PrairieLearn/blob/440bad12fa5afdc84d4c4a3fc652645b1cbcb62d/sync/fromDisk/assessments.js#L279-L285

We could consider printing all errors and warnings after the sync instead?

**Comment by mwest1066** [comment]
I'd be fine with printing all errors/warnings after the sync if that's easier, or just printing these extra ones that never got printed (maybe add a flag indicating it still needs to be printed?). Basically whatever is easier and more robust works for me.
