### ISSUE TITLE
Add a dependency in server.js

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#66]
I am trying to add helper.js to my server.js file:
 
define(["sylvester", "text!./question.html", "text!./answer.html", "SimpleClient", "SimpleFigure", "PrairieGeom","./helper.js"], function(Sylvester, questionTemplate, answerTemplate, SimpleClient, SimpleFigure,PrairieGeom,helper) { 

but I get the error:

U:\GitHub\PrairieLearn\backend>node server
Starting PrairieLearn server...
PrairieLearn server ready
2015-07-23T14:49:07.131Z - error: requirejs load error errorMsg=Error: Tried loa
ding "helper.js" at helper.js then tried node's require("/./helper.js") and it f
ailed with error: Error: Cannot find module '/./helper.js', originalError=Error:
Cannot find module '/./helper.js', moduleName=/./helper.js, requireModules=help
er.js, requireMap=[object Object], requireType=define

**Comment by mwest1066** [comment]
Fixed by adding the concept of a `courseCode` directory in f17f7865a3a2af59a6eed94a73ae32cb7d6d6b59

To use this:

1. Inside `GitHub\pl-tam251` make a new directory called `courseCode`.

2. Put `helper.js` into the `GitHub\pl-tam251\courseCode` directory.

3. Edit the `GitHub\PrairieLearn\config.json` file to add a new line that looks something like:

        "courseCodeDir": "[INSERT-PATH-HERE]\GitHub\pl-tam251\courseCode",

4. Inside both `client.js` and `server.js`, load `helper.js` with something like:

        define([..., "courseCode/helper"], function(..., helper) {
