### ISSUE TITLE
Plan to speed up instructor assessments page

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6647]
At the moment the instructor assessments page can take many seconds to load in large classes (see #6488). This is because we are calling `assessments_stats()` and `assessments_duration_stats()` for each assessment to calculate statistics in real time: https://github.com/PrairieLearn/PrairieLearn/blob/9f7c2b7a3b3f7d57c83dc4d5b781e06214447110/pages/instructorAssessments/instructorAssessments.sql#L58-L59 Each of these calls can take a few hundred milliseconds for an assessment so with hundreds of assessments the page render time can be tens of seconds.

My plan for fixing this is twofold:
1. Cache the results of `assessments_stats()` and `assessments_duration_stats()` in the database (probably a separate table), together with timestamps for when the cache was last updated. Also add an index on `(assessment_id, modified_at)` for the `assessment_instances` table. On the instructor assessments page, for each assessment check whether there are any assessment instances where `modified_at` is greater than the cache update time and recalculate those statistics (and update the cache).
2. On the instructor assessments page, if there are assessments where the cache is not up to date, simply mark those assessments as requiring a recalculation but don't actually do it. Send all the data to the client, and then have the client lazy-load the missing statistics via ajax calls, which will recalculate/re-cache as needed on the server.

The reason for step (2) above is that, if students are actively working on a few assessments, recalculating the statistics could still take a second or two, which is undesirably slow for a page load.

**Comment by nwalters512** [comment]
I'm curious about step 2. You say "recalculating the statistics could still take a second or two" - do we actually observe individual assessments where those computations take that long? I guess I was thinking that individual ones might be fast, but the problem is that we're doing a lot of them. Maybe Postgres is parallelizing things such that each one really does take on the order of multiple seconds though?

The above is moreso for my own understanding - I agree that doing things asynchronously makes sense regardless as a hedge against really slow queries. I do wonder if we have to be careful somehow to limit the number of DB connections that can be consumed by a single page load. If we have 10 assessments that need updated stats, the naive implementation will fan that out into 10 network requests and thus 10 DB connections being consumed roughly at the same time. We could briefly find ourselves out of connections on that host.

Everything else sounds sensible. It's unfortunate that we'll need another index, but that's understandable - the thinking there is that we can determine if there are outdated stats by looking *only* at the index, right?

**Comment by mwest1066** [comment]
Sounds reasonable, I'll do (1) first and then see how things look.
