### ISSUE TITLE
Indicate insufficient precision with client-side JS

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#710]
For numeric input elements, client-side JavaScript could detect when the input values have insufficient precision and indicate this, for example by turning the notification button on the input element red.

**Comment by eliotwrobson** [comment]
Seems to overlap with #3708. This issue is currently handled by the number/integer input elements giving an invalid message if they get an input which is too large after submission (see screenshot).

![image](https://github.com/PrairieLearn/PrairieLearn/assets/1345068/047ffad3-5558-4018-b37c-2dc83847a3fb)

@mwest1066 should we go ahead and close this? I don't think there's a huge benefit to adding this functionality to the client-side.

**Comment by mwest1066** [comment]
I think the intent of this issue was more about precision rather than range. For example, if we have a `pl-number-input` with `rtol=1e-3` and a student enters `1.2` as the submitted answer, we could warn them that they only have about 0.1 precision which is likely to not be enough for the question.

**Comment by mwest1066** [comment]
I should say that I definitely don't think that we should do this client-side. This could easily be a server-side thing, if we wanted to do it at all. If we did do something like this then I would suggest doing this only as feedback for incorrect answers.

**Comment by eliotwrobson** [comment]
Ahhh, that makes more sense to me. It might actually be straightforward to add that piece of feedback to the element in cases like these (just a check of student answer vs relative tolerance and displaying a short message). It may be worth including in #7934, as this change would only be a few lines of code.

**Comment by mwest1066** [comment]
> It might actually be straightforward to add that piece of feedback to the element in cases like these (just a check of student answer vs relative tolerance and displaying a short message). It may be worth including in #7934, as this change would only be a few lines of code.

That would be cool if it's easy to add!
