### ISSUE TITLE
Simplify display of the "format_error" 

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#7345]
Creating an issue for feedback on this: if there's a format error assigned, would it be better to make the `invalid` button directly clickable with the format_error message (rather than a `why`)?

Even better, I feel that format errors should be displayed **much more prominently** to let students know that they need to read the message and act on it.

<img width="500" alt="Screenshot 2023-03-16 at 12 28 37 AM" src="https://user-images.githubusercontent.com/2507459/225514751-3977d2d6-22ba-43cf-a0f5-730405270062.png">

Personally I like the idea of what we do with the Manual Grading (just with a different colour (red?)):

<img width="971" alt="Screenshot 2023-03-16 at 12 38 33 AM" src="https://user-images.githubusercontent.com/2507459/225515938-49a3b9fc-ceca-4dd6-b373-0f2c6ace2d37.png">

**Comment by eliotwrobson** [comment]
The way that this is displayed is actually copied and pasted among all of the elements, so it's a bit hard to change all at once. Maybe in the same vein as https://github.com/PrairieLearn/PrairieLearn/pull/5901, we should initiate some more detailed discussion about the best standard ways to display format errors, correctness badges, etc., and then implement those changes across all the elements. (See https://github.com/PrairieLearn/PrairieLearn/issues/5369 for another issue about uniformity).

I think uniformity of options (like https://github.com/PrairieLearn/PrairieLearn/issues/878) and how elements are displayed (like in this issue) are worth handling together, since they both deal with trying to have all of the existing elements behave similarly. @firasm maybe the best thing to do is make a discussion item collecting these similar minor issues, and then have a checklist there of elements that need updating?

**Comment by firasm** [comment]
Totally agree - let's do that. There are half a dozen of these minor annoyances that I want to collect in one place and organize a coordinated effort to address (btw thank you for taking #6775 (née #6041) closer to the finish line!

**Comment by eliotwrobson** [comment]
@firasm I'm starting to apply the various items from the element consistency issues. Do you happen to have HTML that does the behavior you'd like to see with the format error? Personally, I think the best / simplest thing would be to just make the red "invalid" box in the first image you posted clickable with that same popover, and just remove the "Why?" button.

**Comment by firasm** [comment]
Hi @eliotwrobson - a few comments:

- I agree, the `Why?` button should be removed and the `invalid` should just be clickable with a popover
- IMHO, the popover should be displayed by default (if there is a format error). That should be possible with [popover('show')](https://getbootstrap.com/docs/4.1/components/popovers/#popovershow) but I hope that doesn't run afoul of other PrairieLearn conventions
- For element consistency, the sympy element should also behave this way.

I had hacked together an alert like this:

<img width="830" alt="Screenshot 2023-05-27 at 12 54 16 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/d08633b0-c509-4b2e-bc88-046131cce01a">

Here's how I implemented the above using moustache templating:

```
{{#format_errors.invalid}}
<div class="alert alert-danger" role="alert">{{.}}</div>
{{/format_errors.invalid}}

{{#submitted_answers.repo_url}}

{{^format_errors.invalid}}
<div class="alert alert-success" role="alert">Your submission was: {{ submitted_answers.repo_url }}</div>
{{/format_errors.invalid}}

{{/submitted_answers.repo_url}}
```

Thanks for taking care of this!

**Comment by eliotwrobson** [comment]
This has now been done for all of the most commonly used text input elements:

- pl-string-input
- pl-symbolic-input
- pl-big-o-input
- pl-integer-input
- pl-number-input
- pl-units-input

Any input elements less actively maintained and not covered by this will have this feature included as part of follow-up refactor PRs.

**Comment by firasm** [comment]
Thanks @eliotwrobson amazing!
