### ISSUE TITLE
Fix question titles on student exam question pages

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#778]

**Comment by trombonekenny** [comment]
Is this that the question title is empty for the student view of questions in mode: exam?

**Comment by mwest1066** [comment]
Yep!

**Comment by trombonekenny** [comment]
I would use the title for this, but since it's broken, maybe you know of a workaround.

When viewing the student's view of the question, how can I easily map that back to which question it is? We don't see any zone or qid or title information to tie it back to, say, the question itself or the student's assessment log behavior about that question.

I wonder if we could make a link to those somewhere in the question if you're viewing with admin permissions?

**Comment by trombonekenny** [comment]
The question number is good.

The question title should be removed in exams. The thinking is to "obscure" it a bit more so it's harder for students to cheat.

**Comment by mwest1066** [comment]
Same as #1149
