### ISSUE TITLE
Give each course its own Python virtual env for executing question code

### ISSUE THREAD

**Issue by eliotwrobson** [PrairieLearn/PrairieLearn#8182]
See title, idea that came up during OH. Probably requires setting up Mamba for lockfile support and faster environment solving.

**Comment by nwalters512** [comment]
A more realistic vision for this is that a course can point us to a Dockerfile to use as their question runtime. The primary problem with using virtual environments would be that they'd lead to long "cold starts" when dependencies need to be installed on a new chunk server. There are other potential problems, for instance, installation of deps could fail due to a transient network issue or PyPi downtime, and we'd have to be able to recover gracefully from that.

Allowing courses to specify their own environment raises an interesting question: what context do core elements run in?

- If we run them in the "standard" PL Python environment, course element extensions could try to load something that isn't in the global environment (we could of course just document that course element extensions always run in the standard env). Also, the new question processing introduced in #7128 wouldn't be possible since we'd have to run code in two separate containers.
- If we run core elements in the course environment, they'd always certainly run into issues where core elements depend on some library that doesn't exist in a course's environment.

And regardless of what we do, even with Docker images, we'd run into cold start issues because we'd need to load the image and boot a container each time a server handles a request for a given server for the first time. Maybe we have stateful execution servers where we can always route requests for a particular course to a particular server/container? We are now basically re-implementing a shitty version of Lambda or https://fly.io.

**Comment by eliotwrobson** [comment]
These are all very good points, it makes sense that we'd need something a little more portable than just an environment file. Also, the point about what environment questions run in is very important (both from a technical standpoint, and keeping the mental model of what is happening in PL as simple as possible).

Although I copied down this idea for an issue because of the discussion in OH, I'm not sure how many people are running into issues with this in general. Especially with the implementation of a more flexible deployment architecture for the python autograder, I don't know what the demand for something like this would be. This is definitely something that can go on the backburner until there is greater demand or the architecture of PL makes it simpler to implement.

**Comment by nwalters512** [comment]
I'm going to close this. Something like this would require huge changes to our infrastructure to run in a way that performs reasonably well for end users.

Though it doesn't achieve exactly the same goal of allowing completely arbitrary execution environments, I'd consider #10097 to be the successor of this issue.
