### ISSUE TITLE
`pl-python-variable` with `compact` attribute does not work inside `pl-question-panel`

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8467]
Reported by @ffund

The following example gives the error `Exception: Attribute "compact" must be a boolean value:` -- note that there is nothing following the last colon, which is where the attribute value is printed. Removing the `compact` attribute makes the problem go away. Keeping `compact` but shifting the `pl-python-variable` element outside of the `pl-question-panel` also makes the error go away.

```
<pl-question-panel>
    <pl-python-variable compact="true" params-name="x"></pl-python-variable>
</pl-question-panel>
```

**Comment by nwalters512** [comment]
A breadcrumb: add `print(element_html)` immediately before this line:

https://github.com/PrairieLearn/PrairieLearn/blob/32d6d53c1714a4bdab7d51be890e37942878c8a4/apps/prairielearn/elements/pl-python-variable/pl-python-variable.py#L30

Observe that the following is printed before the error:

```
<pl-python-variable compact="" params-name="x"></pl-python-variable>
```

As it turns out, we have `libxml2` to blame for this!

https://gitlab.gnome.org/GNOME/libxml2/-/blob/4aa08c80b711ab296f6e6ecab24df8cf6d0be5fc/HTMLtree.c#L306

**Comment by eliotwrobson** [comment]
It should be straightforward to rename the variable and use a passthrough. I can do this quickly when I have a few minutes.
