### ISSUE TITLE
Add `--sync-course` command line option

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#8797]
To support auto-sync of the example course on deploy it would be great to have PL support a `--sync-course=<course_id>` command line option. This should sync the given course and then exit.

**Comment by jonatanschroeder** [comment]
I did a quick check at the main process for this functionality (which for some reason [is in `pages/shared`](https://github.com/PrairieLearn/PrairieLearn/blob/0f568e390c065327b67dc0cfae49ba92477007fe/apps/prairielearn/src/pages/shared/syncHelpers.js#L23) instead of `lib`), and it relies a lot on `res.locals`. All references seem to be relatively simple to retrieve from DB, but it may be a better idea to first move some of this functionality to a lib that doesn't depend on `res.locals`, then call it from the shared code with the appropriate values from locals. This could be done in [the `courseUtil` lib](https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/src/lib/courseUtil.js).

The job sequence created for this process requires a user ID, should this be hardcoded to 1? I don't think it matters much, but just raising it.
