### ISSUE TITLE
Better access control over course question bank

### ISSUE THREAD

**Issue by natepark01** [PrairieLearn/PrairieLearn#8850]
With the recent changes to the staff access control, we're able to designate course-level viewers and editors, as well as instance level student access viewers/editors.

However, this is very misleading because setting course content access to None and instance level student data access to Viewer essentially gives access to the course content in its entirety, making the Course Content Access setting essentially moot.

It might be important for many courses, especially CS courses where it is very helpful for course staff to have access to student data but not the entire question bank, to have this kind of control.

I think the current behavior of setting Course Content Access to None should be changed to restrict access to the course question bank.

**Comment by jonatanschroeder** [comment]
Continuing the discussion from https://github.com/PrairieLearn/PrairieLearn/pull/8843#discussion_r1394895345. Listing the pages associated to course admin (instead of course instance admin), here's some initial thoughts on restrictions for users with course instance access but no course access:

* Assessment Sets, Tags, Topics: I don't see an issue with these users having access to this information, but there's nothing that they would gain from having that info, since these users cannot create/manage assessments/questions anyway.
* Course Instances: this page already restricts the list to those that the user has access to, so either keeping or blocking should be fine.
* Files, Staff, Sync: these pages are already blocked for users based on course permissions (requires Viewer, Owner and Editor, respectively).
* Settings: I don't see a value in providing access to this page.
* Sharing: ditto.

* Issues: this one may be an interesting case. I see the use-case of TAs responding to issues raised by students in their course instances. The page already checks if the user has access to the course instance associated to the issue, and if it does it hides the links to student view, manual grading and assessment log. However, should these users have access to issues in other course instances at all? Should the page be visible to these users and, if so, be changed to only list, for these users, issues associated to instances they have access to?

* Questions (from https://github.com/PrairieLearn/PrairieLearn/pull/8843#discussion_r1394904357): do these students actually need question preview access? If so, what filter should be done to only allow access to questions that are in assessments in their own course instances? If preview should be denied, then links to "instructor view" (see comment above) should be removed too.

**Comment by mwest1066** [comment]
> * Assessment Sets, Tags, Topics: I don't see an issue with these users having access to this information, but there's nothing that they would gain from having that info, since these users cannot create/manage assessments/questions anyway.

I agree we could just block this.

> * Course Instances: this page already restricts the list to those that the user has access to, so either keeping or blocking should be fine.

Again, we could just block.

> * Files, Staff, Sync: these pages are already blocked for users based on course permissions (requires Viewer, Owner and Editor, respectively).

Perfect.

> * Settings: I don't see a value in providing access to this page.

Agreed.

> * Sharing: ditto.

Agreed.

> * Issues: this one may be an interesting case. I see the use-case of TAs responding to issues raised by students in their course instances. The page already checks if the user has access to the course instance associated to the issue, and if it does it hides the links to student view, manual grading and assessment log. However, should these users have access to issues in other course instances at all? Should the page be visible to these users and, if so, be changed to only list, for these users, issues associated to instances they have access to?

I think we'd ideally make this page visible to course-instance-only users but filter it down to only issues associated with their accessible course instances.

> * Questions (from [Remove course and course instance queries from authz middleware #8843 (comment)](https://github.com/PrairieLearn/PrairieLearn/pull/8843#discussion_r1394904357)): do these students actually need question preview access? If so, what filter should be done to only allow access to questions that are in assessments in their own course instances? If preview should be denied, then links to "instructor view" (see comment above) should be removed too.

I think the simplest thing would be to block access to the Questions page and to all instructor question routes. It's going to be very messy to try and figure out whether such a user should be able to access the instruction question preview for a specific question, based on which assessments that question has been used in. Simply removing all the "instructor view" links (and blocking the routes) seems easiest to me?

**Comment by jonatanschroeder** [comment]
> I think we'd ideally make this page visible to course-instance-only users but filter it down to only issues associated with their accessible course instances.

Since this would be the only course-admin page that is accessible to these users, would it make sense to add an "Issues" tab to the course instance that includes only the issues for the current course instance? Not sure if this is a good idea or if this could cause confusion to users that have course permissions and have access to both pages.

> I think the simplest thing would be to block access to the Questions page and to all instructor question routes. It's going to be very messy to try and figure out whether such a user should be able to access the instruction question preview for a specific question, based on which assessments that question has been used in. Simply removing all the "instructor view" links (and blocking the routes) seems easiest to me?

All pages that link to the questions page or any of the instructor individual question routes (preview, files, settings, stats) from pages that this kind of user would presumably have access to:
* The navbar (includes links for Questions and Sync at the top);
* Assessment questions page;
* Assessment instance page (instructor view in question list, question stats, log);
* Assessment question stats page;
* Issues page;
* The instructor panel in instance questions.

**Comment by nwalters512** [comment]
Resolved by #10591.
