### ISSUE TITLE
Assessment instance logs sorted incorrectly by default

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#9062]
Someone reported at least two instances where the logs for an assessment instance weren't sorted correctly:

- https://us.prairielearn.com/pl/course_instance/139940/instructor/assessment_instance/6680572
- https://us.prairielearn.com/pl/course_instance/139940/instructor/assessment_instance/6680521

In each case, the logs aren't ordered in increasing timestamp order. We should fix this.

**Comment by jonatanschroeder** [comment]
It seems some sorting change was done in #4797, but that sort happens inside a CTE for some reason:

https://github.com/PrairieLearn/PrairieLearn/blob/1879d7d17361f7ee4d8954c7c294268aaef009c0/apps/prairielearn/src/lib/assessment.sql#L703-L708

I'd guess that some change in how Postgres reads that CTE probably made this order be lost between the CTE and the main query. Regardless of the reason, that sort should probably go to the end of the query, to the main SELECT statement instead of the CTE.
