### ISSUE TITLE
Institution dropdown is not sorted

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#9433]
On the admin courses page, for the approve course request dialog, the institution dropdown lists the institutions in non-alphabetical order (and only the short names). We should sort this and maybe also list the long names as well or instead, for clarity.

**Comment by harivamsi9** [comment]
Just an idea (please correct me if I am wrong, or missing anything): 

Can we simply sort them directly when we query from the database using ORDER BY ___ ASC; ? I assume we run the query from administratorCourses.sql file. 

I am still understanding the codebase, so please correct me or guide me to the proper file otherwise. I would love to contribute to this

**Comment by nwalters512** [comment]
That's exactly what to do. Here's the query:

https://github.com/PrairieLearn/PrairieLearn/blob/aefa9184d691c78db7064abdcfdb9d7db04873a5/apps/prairielearn/src/models/institution.sql#L20-L24

Prior art with the desired sort order:

https://github.com/PrairieLearn/PrairieLearn/blob/aefa9184d691c78db7064abdcfdb9d7db04873a5/apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.sql#L22-L25
