### ISSUE TITLE
pl-code inside pl-answer-panel renders incorrectly after submitting answer

### ISSUE THREAD

**Issue by myriath** [PrairieLearn/PrairieLearn#9570]
I am sorry if this has been discussed before, I did a little searching through the issues and couldn't find anything.

It seems as though (rather arbitrarily) if you use pl-code elements inside of a pl-answer-panel element, it will not render the border and background and adds line numbers sometimes.

I have only seen this happen on questions that are externally graded, and the issue fixes itself after a page reload.

Preliminary investigation yields it might only be occurring when the pl-code is the only thing in the answer-panel?

System: PL running on WSL Ubuntu 22.04, Browser is Firefox 123.0.1 (64-bit)

# Examples
### Example before reloading:
![Before reload 0](https://github.com/PrairieLearn/PrairieLearn/assets/31975310/8cf7dede-f8f7-4e2b-9d94-e88f1f23a038)

![Before reload 1](https://github.com/PrairieLearn/PrairieLearn/assets/31975310/8acb3a26-29e5-4d99-8d33-28a51822e847)

### Example after reloading:
![After reload 0](https://github.com/PrairieLearn/PrairieLearn/assets/31975310/0dd2817f-29fe-4b3c-9ecb-2b9764779c05)

![After reload 1](https://github.com/PrairieLearn/PrairieLearn/assets/31975310/8026c442-375b-4622-9a07-da5a63aecb1a)

### Example correctly rendering first try:
![Correct example](https://github.com/PrairieLearn/PrairieLearn/assets/31975310/8ecd4ad0-4133-487a-aea0-ab2e715b4eaa)

### Question code used for above examples
[RendersCorrectly.zip](https://github.com/PrairieLearn/PrairieLearn/files/14531330/RendersCorrectly.zip)
[RendersIncorrectly0.zip](https://github.com/PrairieLearn/PrairieLearn/files/14531331/RendersIncorrectly0.zip)
[RendersIncorrectly1.zip](https://github.com/PrairieLearn/PrairieLearn/files/14531332/RendersIncorrectly1.zip)

**Comment by jonatanschroeder** [comment]
I'm wondering if any dependencies are not loaded when the panels are loaded via socket...

**Comment by nwalters512** [comment]
Yeah, I think that's exactly the problem here. The reason that the `RendersCorrectly.zip` question works correctly is that there's a `<pl-code>` rendered in the question panel, so the necessary styles are available when the answer panel renders, but that's not true for the other two questions. And this is really only a problem with the answer panel; for the submission panel, that's rendered as part of the initial page load, so (barring conditional rendering of elements) we already know which elements we need to load dependencies for.

Easy fix: if we load a non-empty answer panel via a websocket, show a "reload page to view" button.

Hard fix: actually handle the asynchronous loading of element dependencies correctly. This will require some careful handling to do this correctly during deploys and course modifications; we'll want to detect when the version of a dependency has changed and perform a full page reload if necessary.

**Comment by nwalters512** [comment]
@myriath if you're looking for an immediate, hacky fix: include something like this so that it's rendered in the question panel:

```html
<div style="displa:none;"><pl-code></pl-code></div>
```

This is untested, but it should ensure that all the right styles are loaded before the answer panel is.

**Comment by myriath** [comment]
@nwalters512 yes, that does fix the problem, thanks!
