### ISSUE TITLE
Error creating python worker error when trying to run PrairieLearn

### ISSUE THREAD

**Issue by TylerWeberski** [PrairieLearn/PrairieLearn#9702]
When installing PrairieLearn and trying to run my course which has been worked on, I am getting this error. Was re-installing virtual machine, so reset my terminal and now getting this error after try to run docker
![Screenshot 2024-04-08 151317](https://github.com/PrairieLearn/PrairieLearn/assets/78037865/e54d42d6-0baa-48e1-b557-27c98b158fbe)

**Comment by nwalters512** [comment]
Can you share more information about your environment, including OS, OS version, CPU architecture, and Docker version?

**Comment by TylerWeberski** [comment]
I'm using Linux Ubuntu 22.04 LTS (Jammy Jellyfish) (64-bit) through the Oracle VM VirtualBox. My docker version is 26.0.0

**Comment by nwalters512** [comment]
`SIGILL` means that the underlying hardware is treating an instruction as malformed, unsupported, etc. Given that PrairieLearn has no problem executing natively on macOS, Windows, or Linux, I'm inclined to call this an issue with VirtualBox. If you can find any evidence to point to a potential problem with PrairieLearn, we'd be happy to accept a fix. Otherwise, I'll go ahead and close this issue.

Are you able to run PL natively, outside of a VM? You can do it either via Docker or directly on the host, both are very well-supported.

**Comment by TylerWeberski** [comment]
Yea I think it was a VirtualBox issue, although I had it working there before, running it on Windows with the documentation setup for WSL, the issue was resolved. Thanks for the help!

**Comment by nwalters512** [comment]
🙌 glad to hear that worked for you!
