### ISSUE TITLE
Assessments required for a course instance?

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#999]
Check to make sure we're not erroring when a courseInstance exists but doesn't have any assessments defined (or the structure for assessments-- it was unclear from Andre's report).

**Comment by rbessick5** [comment]
I think I've observed the error behavior that this issue is concerned with: the directory `assessments` must exist (if it does not, PL errors on sync), but can be empty.

I can make a little edit to https://prairielearn.readthedocs.io/en/latest/courseInstance/ and push a PR to clarify this requirement.
